### ISSUE TITLE
Gracefully handle cases when a Mutex can't be created at startup

### ISSUE THREAD

**Issue by onedr0p** [slskd/slskd#1004]
Hi 👋🏼 

I am trying to run slskd with the following options set in Kubernetes:

```yaml
       container:
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups: [10000]
```

## Logs

1. The first one I ran into was this one which was easily to solve by adding a emptyDir mount to `/.net/slskd`

```
❯ k logs slskd-7dc978f9d8-r9h65
Failure processing application bundle.
Failed to create directory [/.net/slskd/] for extracting bundled files.
```

2. The second one is a bit more cryptic and I am not sure how to make it work:

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'slskd.Program' threw an exception.
 ---> System.IO.IOException: The system cannot open the device or file specified. : '42335EE2DA436D3907CE87E372511838B58E284E8225E9722251DCDC3BDB8FEA'
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at slskd.Program..cctor()
   --- End of inner exception stack trace ---
   at slskd.Program.Main(String[] args)
```

My guess is that is really doesn't like `readOnlyRootFilesystem: true` being set because when I remove that, it works.

**Comment by onedr0p** [comment]
I came across t[his issue](https://github.com/PowerShell/PSReadLine/issues/1464#issuecomment-631015069) which my me think to set an emptyDir on `/tmp` as well and that solved the issue.

**Comment by onedr0p** [comment]
I'm curious if there's also a way to put this in tmp as well? `/.net/slskd`. It would allow me to mount less volumes on a r/o filesystem.

**Comment by jpdillingham** [comment]
I think it's worth a shot; it's set by `DOTNET_BUNDLE_EXTRACT_BASE_DIR` and I'm pretty sure I chose the location somewhat arbitrarily.

**Comment by onedr0p** [comment]
Oh nice, I should have looked at the dockerfile before asking. Changing that to `/tmp/.net` worked great.
