### ISSUE TITLE
Disconnected from the Soulseek server: Failed to connect: Did not receive one or more expected server messages upon login

### ISSUE THREAD

**Issue by morganther** [slskd/slskd#1077]
slskd canary and latest both fail to start with this error:

```
Disconnected from the Soulseek server: Failed to connect: Did not receive one or more expected server messages upon login
[slskd.Application] [06:54:30 INF] Waiting about a second before reconnecting
[Microsoft.Extensions.Hosting.Internal.Host] [06:54:30 ERR] Hosting failed to start
Soulseek.SoulseekClientException: Failed to connect: Did not receive one or more expected server messages upon login
 ---> Soulseek.ConnectionException: Did not receive one or more expected server messages upon login
 ---> System.TimeoutException: The wait timed out after 5000 milliseconds
   at Soulseek.SoulseekClient.ConnectInternalAsync(String address, IPEndPoint ipEndPoint, String username, String password, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Soulseek.SoulseekClient.ConnectInternalAsync(String address, IPEndPoint ipEndPoint, String username, String password, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Soulseek.SoulseekClient.ConnectInternalAsync(String address, IPEndPoint ipEndPoint, String username, String password, CancellationToken cancellationToken)
   at slskd.Application.Microsoft.Extensions.Hosting.IHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
```

The Seeker Android app works for the same account (but different IP addresses)

**Comment by jpdillingham** [comment]
@mathiascode any thoughts on [this](https://github.com/jpdillingham/Soulseek.NET/blob/master/src/SoulseekClient.cs#L2985)? The logic is waiting for 'parent min speed', 'parent speed ratio' and 'wishlist interval'.  Any knowledge of why the server wouldn't send one or more of those?

@morganther interestingly this error is being raised from the [Soulseek.NET](https://github.com/jpdillingham/Soulseek.NET/blob/master/src/SoulseekClient.cs#L2985) library which is what the Seeker implementation is based off of.

**Comment by mathiascode** [comment]
> @mathiascode any thoughts on [this](https://github.com/jpdillingham/Soulseek.NET/blob/master/src/SoulseekClient.cs#L2985)? The logic is waiting for 'parent min speed', 'parent speed ratio' and 'wishlist interval'. Any knowledge of why the server wouldn't send one or more of those?

Looks fine. I haven't seen any case where the messages wouldn't be sent when the login succeeds. Is there any logging of incoming messages and their contents?

**Comment by jpdillingham** [comment]
@morganther can you try with the new [0.20.0](https://github.com/slskd/slskd/releases/tag/0.20.0) release? I refactored some things in Soulseek.NET so that the login process is no longer dependent upon these messages.

**Comment by morganther** [comment]
@jpdillingham yes i can confirm 0.20 works :) thank you so much!

**Comment by mathiascode** [comment]
Can this issue be closed?

**Comment by morganther** [comment]
> Can this issue be closed?

Yes, thank you and apologies for the delay
