### ISSUE TITLE
Keep slskd running even if internet is not available (vps.slsknet.org)

### ISSUE THREAD

**Issue by apkatsikas** [slskd/slskd#1093]
My Raspberry Pi restarted because of a power outage, and I noticed when the power returned that slskd was not running. The logs show:

```
Mar 07 21:01:07 raspberrypi slskd[557]: [21:01:07 FTL] Application terminated unexpectedly
Mar 07 21:01:07 raspberrypi slskd[557]: Soulseek.AddressException: Failed to resolve address 'vps.slsknet.org': Resource temporarily unavailable
Mar 07 21:01:07 raspberrypi slskd[557]:  ---> System.Net.Sockets.SocketException (00000001, 11): Resource temporarily unavailable
Mar 07 21:01:07 raspberrypi slskd[557]:    at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, Int64 startingTimestamp)
Mar 07 21:01:07 raspberrypi slskd[557]:    at System.Net.Dns.GetHostEntry(String hostNameOrAddress, AddressFamily family)
Mar 07 21:01:07 raspberrypi slskd[557]:    at Soulseek.SoulseekClient.ConnectAsync(String address, Int32 port, String username, String password, Nullable`1 cancellationToken)
```

Because the internet was not available when the Pi turned back on, slskd failed to start up. Ideally, slskd will keep running even if internet access is not available.

**Comment by jpdillingham** [comment]
Not sure why I never responded to this.  The automatic reconnect logic should work the same regardless of whether the client connects and then disconnects, or can't connect initially.  Probably an easy fix somewhere; I'm looking into it now.

**Comment by jpdillingham** [comment]
@apkatsikas have you seen this happen recently? I remember investigating at the time and couldn't reproduce

**Comment by apkatsikas** [comment]
> [@apkatsikas](https://github.com/apkatsikas) have you seen this happen recently? I remember investigating at the time and couldn't reproduce

I ended up leveraging the --no-connect flag which prevents slskd from connecting on startup and gets me my desired behavior.
