### ISSUE TITLE
Download error: The wait timed out after 5000 milliseconds (HTTP 500)

### ISSUE THREAD

**Issue by F2FG** [slskd/slskd#1144]
Since today I get this error, The wait timed out after 5000 milliseconds (HTTP 500), every time I try to download a file.

![Screenshot from 2024-06-02 20-58-42](https://github.com/slskd/slskd/assets/50996306/58abf601-95a7-43cc-b35e-90dacba65596)

Does anybody know how to solve this issue?

**Comment by jpdillingham** [comment]
That error generally indicates that the connection to the other user couldn't be made.  You can try increasing the timeout ([docs](https://github.com/slskd/slskd/blob/master/docs/config.md#timeouts)) and see if that helps.  If you've gotten search results from this user you should be able to connect, but their client/computer might be busy or the network between the two of you congested.

If you're no longer able to get search results then there may be a configuration issue somewhere (firewall perhaps?)

**Comment by F2FG** [comment]
Thank you for your help!

> If you're no longer able to get search results then there may be a configuration issue somewhere (firewall perhaps?)

Until a few minutes ago I was able to get search results, right now I can't. I checked the connection and the port and everything is working correctly. I checked in the logs and now I see this:

Failed to execute post-login actions: System.TimeoutException: The wait timed out after 5000 milliseconds at Soulseek.SoulseekClient.GetUserStatisticsInternalAsync(String username, CancellationToken cancellationToken) at slskd.Application.RefreshUserStatistics(Boolean force) at slskd.Application.Client_LoggedIn(Object sender, EventArgs e)

**Comment by F2FG** [comment]
I also tried to increase the timeout:

   connection:
     timeout:
       connect: 20000
       inactivity: 30000

It's not helping.

**Comment by dkschruteBeets** [comment]
I too, am seeing the same:

![image](https://github.com/slskd/slskd/assets/103469370/ab15afde-cecb-4214-88ed-ee98ad58c80c)

**Comment by F2FG** [comment]
> I too, am seeing the same:

Are you running Slskd behind a VPN? I found out that I run into this only when I use a VPN, even if it's configured correctly. My VPN provider is AirVPN. This issue started very recently, everything worked correctly until a few days ago.

I read that last week Soulseek was under a DDoS attack, is it possible that the solution used by the protocol against the attack is causing this issue?

**Comment by dkschruteBeets** [comment]
> > I too, am seeing the same:
> 
> 
> 
> Are you running Slskd behind a VPN? I found out that I run into this only when I use a VPN, even if it's configured correctly. My VPN provider is AirVPN. This issue started very recently, everything worked correctly until a few days ago.
> 
> 
> 
> I read that last week Soulseek was under a DDoS attack, is it possible that the solution used by the protocol against the attack is causing this issue?

I am actually. I just signed up for AirVPN a few days ago for the port forwarding feature. Like you said, everything is configured correctly on my end too. I didn't know about the DDoS attack.

**Comment by F2FG** [comment]
> I am actually. I just signed up for AirVPN a few days ago for the port forwarding feature.

I guess we found out what's happening then, and it's not good to hear. They are probably filtering incoming traffic from AirVPN servers.

I can tell you that if you stop using AirVPN Slskd should work.

**Comment by sturia** [comment]
+1
I have exactly the same problem, this started few days ago. Didn't change anything in network setup and slskd has direct access to internet - any chance to troubleshoot this further? searching works perfectly
thanks

**Comment by jpdillingham** [comment]
Couple of things that might be contributing:

* The Soulseek server has been under a direct DDoS attack per Nir in [this reddit thread (thanks @mathiascode)](https://www.instagram.com/thecenteredlifeco/reel/C1FDwQjrX9G/)
* The 0.21.0 release included a new P2P black/blocklist feature that _almost certainly_ is not the culprit, but I'll review the code changes and see if I can find anything (assume this isn't the case if I don't report back)

I downgrading to 0.20.1 or earlier would rule out any recent changes causing the issue.  If those that are impacted could try that and let me know the outcome I'd appreciate it.

**Comment by F2FG** [comment]
>     * The Soulseek server has been under a direct DDoS attack per Nir in [this reddit thread (thanks @mathiascode)](https://www.instagram.com/thecenteredlifeco/reel/C1FDwQjrX9G/)

You probably pasted the wrong link :)

> I downgrading to 0.20.1 or earlier would rule out any recent changes causing the issue. If those that are impacted could try that and let me know the outcome I'd appreciate it.

I set up Slskd in a VM and I have a backup of it before updating, so it was very easy to proceed. Nothing changes, I get the same error. Here you have the few interested lines from the logs:

16:43:46	INF	Version: "0.20.1.0 (0.20.1.0+0e3bea64)
16:44:27	INF	Connected to the Soulseek server
16:44:27	INF	Logged in to the Soulseek server as "XXXXX
16:44:32	ERR	Failed to execute post-login actions: System.TimeoutException: The wait timed out after 5000 milliseconds at Soulseek.SoulseekClient.GetUserStatisticsInternalAsync(String username, CancellationToken cancellationToken) at slskd.Application.RefreshUserStatistics(Boolean force) at slskd.Application.Client_LoggedIn(Object sender, EventArgs e)

Thank you very much for your help!

**Comment by jpdillingham** [comment]
Thanks, that could have been bad 🤦 

That error definitely indicates server issues.

**Comment by 2cin** [comment]
I'm also receiving this error but with uploads. Used to be not as common but has become more prevalent recently. I can provide logs if needed. Changing timeout in settings does not resolve issue (error message still says 5000ms)

**Comment by dkschruteBeets** [comment]
My issue seems to be resolved. I changed the server port to 4910 and things started to move.

**Comment by F2FG** [comment]
> My issue seems to be resolved. I changed the server port to 4910 and things started to move.

I tried port 4910 and I run into the same issue:

Connection via AirVPN servers: not working (ERR Failed to execute post-login actions)
Connection without VPN: working

**Comment by dkschruteBeets** [comment]
> > My issue seems to be resolved. I changed the server port to 4910 and things started to move.
> 
> I tried port 4910 and I run into the same issue:
> 
> Connection via AirVPN servers: not working (ERR Failed to execute post-login actions) Connection without VPN: working

Might be worth opening the original client and trying out some of the predefined server ports and see what sticks perhaps?

![image](https://github.com/slskd/slskd/assets/103469370/cdf753fa-df12-47cd-a978-4e58656dd7b9)

**Comment by dror3go** [comment]
> My issue seems to be resolved. I changed the server port to 4910 and things started to move.

@dkschruteBeets Can you please elaborate which configuration in the docker compose file you've changed to accomplish this?

**Comment by sturia** [comment]
tried several (not all) of the server ports of the original client but none worked - still reporting the same timeout error :(

**Comment by dkschruteBeets** [comment]
> > My issue seems to be resolved. I changed the server port to 4910 and things started to move.
> 
> @dkschruteBeets Can you please elaborate which configuration in the docker compose file you've changed to accomplish this?

System > Options > Edit > Under the "soulseek" header, change the port value:

<img width="315" alt="image" src="https://github.com/slskd/slskd/assets/103469370/a1fd3e40-b02c-4438-8341-76f4374785ef"><br>

Also, to handle Soulseek traffic, I created firewall rules in pfSense to route traffic to the Soulseek server through the Mullvad VPN gateway. For the listening port, I continue to use AirVPN with port forwarding. Although the setup is complex, it works for me since I already have a Mullvad subscription for my regular home traffic. I likely could have kept using 4910 but I ended up using 2474 while testing and stuck with that.

Hope that helps.

**Comment by F2FG** [comment]
After the last week update I don't run anymore into this issue.

**Comment by jpdillingham** [comment]
Seems like the problem resolved itself.  Feel free to reopen if needed.

**Comment by jpdillingham** [comment]
When you browse a user your client must connect directly to theirs to transfer the data.  If neither user has port forwarding configured properly, the connection won't succeed.

**Comment by TheDuckMan64** [comment]
I'm also experiencing this issue. Using PIA, I've forwarded the listening port and can confirm it is open

<img width="1621" height="1006" alt="Image" src="https://github.com/user-attachments/assets/12a0f895-7b92-4497-aa3e-988c45689a4f" />

**Comment by NyxWinter** [comment]
Same issue. Using ProtonVPN and gluetun. The port is open on port checkers, and from a different machine + account, I can browse my files just fine. The only clearly suspicious thing is that it says my upload speed is 276 KiB/s, while I set it to 2048 in the config, which should be 2 MiB/s. On top of that, my files cannot seem to appear in search results.

**Comment by jpdillingham** [comment]
The value set in the config is the limit.  If transfers are slower than that it's that something between you and the other client is slowing them down.  Timeouts are a fact of life with a P2P application as well.
