### ISSUE TITLE
App terminated unexpectedly (hosting failed to start)

### ISSUE THREAD

**Issue by surtarso** [slskd/slskd#1156]
Hi there,
I'm having trouble starting the service. It has been working for a long time, it stopped working, as far I as I can see, for no reason at all. Did we get some breaking changes in the YAML last update? (21.0)

`[Service] ExecStart=/home/dietpi/slskd/slskd --config /home/dietpi/.local/share/slskd/slskd.yml`
Here is the log of the error:

````
[21:50:55 INF] Version: 0.21.0.0 (0.21.0.0+b33449b0)
[21:50:55 INF] System: .NET 8.0.6, Unix 6.9.5.0, 64 bit, 8 processors
[21:50:55 INF] Process ID: 622214 (64 bit)
[21:50:55 INF] Invocation ID: "b238317d-3e1e-4e37-8146-eda306d6e832"
[21:50:55 INF] Instance Name: SoulSeek
[21:50:55 INF] Configuring application...
[21:50:55 INF] Using application directory /home/dietpi/.local/share/slskd
[21:50:55 INF] Using configuration file /home/dietpi/.local/share/slskd/slskd.yml
[21:50:55 INF] Storing application data in /home/dietpi/.local/share/slskd/data
[21:50:55 INF] Saving application logs to /home/dietpi/.local/share/slskd/logs
[21:51:02 INF] Listening for HTTP requests at http://0.0.0.0:5030/
[21:51:02 INF] Listening for HTTPS requests at https://0.0.0.0:5031/
[21:51:02 INF] Using randomly generated self-signed certificate
[21:51:02 INF] Using base url /soulseek
[21:51:02 INF] Serving static content from /home/dietpi/slskd/wwwroot
[21:51:02 INF] Configuration complete.  Starting application...
[21:51:02 INF] Blacklist disabled
[21:51:02 INF] Application started
[21:51:03 ERR] Hosting failed to start
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See https://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(RelationalDataReader reader, Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithRowsAffectedOnly(Int32 commandIndex, RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__112_0(DbContext _, ValueTuple`2 t)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at slskd.Transfers.Uploads.UploadService.Update(Transfer transfer)
   at slskd.Application.Microsoft.Extensions.Hosting.IHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
[21:51:03 FTL] Application terminated unexpectedly
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See https://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(RelationalDataReader reader, Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithRowsAffectedOnly(Int32 commandIndex, RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__112_0(DbContext _, ValueTuple`2 t)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at slskd.Transfers.Uploads.UploadService.Update(Transfer transfer)
   at slskd.Application.Microsoft.Extensions.Hosting.IHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at slskd.Program.Main(String[] args)
````

Since it's a DB error I tried to force rescan on start but I guess it's not getting to that point... 
Anything I could do?
Already tried reinstalling and the issue persists.

EDIT: Just upgraded to 21.1 and the problem persists.

**Comment by jpdillingham** [comment]
Just realized that I never replied to this; I meant to but must have gotten distracted and not clicked the button.

Can you share more information about your environment? Specifically your hardware (I see dietpi which suggests a SBC), whether you are using a [copy-on-write filesystem](https://github.com/slskd/slskd/blob/master/docs/known_issues.md#devices-using-a-copy-on-write-filesystem-such-as-btrfs-or-zfs) such as BTRFS or ZFS, anything that would cause resource contention of any kind.

The error you are seeing is caused by, essentially, a race condition that should be extremely rare and transient in nature.  The fact that you are seeing it consistently makes me think there is something nuanced about your environment.

This specific logic executes when the application starts to clean up upload and downloads that were active when the application was stopped; do you think there would have been a lot of them?

You should be able to work around this by deleting the `transfers.db` (and `.db-shm`, `.db-wal` if present) and restarting the application, but in doing so you'll lose transfer history.  You might try renaming the file(s) and seeing if the application will start, which will preserve the data.

**Comment by surtarso** [comment]
Hey, thanks for the reply!

I run DietPi on a x86 Desktop PC (my server), It's an old AMD FX-8300 8gb RAM running Debian Bullseye with Kernel 6.9.5 on EXT4 partitions.

I do share a humongous amount of files (around 50k) and I wasn't present when it crashed. So I can't tell for sure if there were active uploads, but probably (I have it set up to clear upload list daily in YAML since it goes out of control quite regularly). No downloads for sure tho, since I rarely download stuff anymore.

I will try deleting those DB files to see if it fixes the issue, thanks for the hint. Transfer history shouldn't be an issue I guess. 

I wonder tho if there is a clear reason why it happened since it's a rare condition.
Could it be a dying harddrive? Or maybe an unclean reboot? (power outage etc)

On a site note, I have been having weird issues on my server where it loses sync with hwclock and updates/upgrades fail until I re-sync them. It is usually around 1 min off, could that screw up the DB insertions/readings?

Thanks in advance, I'll be back in a few after trying what you suggested.

**Comment by jpdillingham** [comment]
Thanks for reporting back!  Glad deleting the database file resolved the issue for you.

I need to take a look at how database interactions work in general; it's been a pretty big source of problems and this is another symptom.

**Comment by jpdillingham** [comment]
And sorry for not answering this:

> I wonder tho if there is a clear reason why it happened since it's a rare condition.
Could it be a dying harddrive? Or maybe an unclean reboot? (power outage etc)

I'm really not sure.  I wouldn't assume a problem unless you are seeing other evidence.
