### ISSUE TITLE
macOS Sequoia: Application terminated unexpectedly

### ISSUE THREAD

**Issue by th3m4dt1t4n** [slskd/slskd#1220]
when I try to launch on my Mac it starts up but then I get this message. it was working a few days ago and the only thing I can think of is that I did update to macOS Sequoia. if anyone can help with this that'd be great

Last login: Mon Sep 23 17:17:08 on console
/Applications/slskd-0/slskd ; exit;
aaron@Aarons-Mac-mini ~ % /Applications/slskd-0/slskd ; exit;

                   ▄▄▄▄         ▄▄▄▄       ▄▄▄▄
           ▄▄▄▄▄▄▄ █  █ ▄▄▄▄▄▄▄ █  █▄▄▄ ▄▄▄█  █
           █__ --█ █  █ █__ --█ █    ◄█ █  -  █
           █▄▄▄▄▄█ █▄▄█ █▄▄▄▄▄█ █▄▄█▄▄█ █▄▄▄▄▄█
╒════════════════════════════════════════════════════════╕
│           GNU AFFERO GENERAL PUBLIC LICENSE            │
│                   https://slskd.org                    │
│                                                        │
│              0.21.4.0 (0.21.4.0+a666532f)              │
└────────────────────────────────────────────────────────┘
[17:17:30 INF] Version: 0.21.4.0 (0.21.4.0+a666532f)
[17:17:30 INF] System: .NET 8.0.8, Unix 15.0.0, 64 bit, 8 processors
[17:17:30 INF] Process ID: 906 (64 bit)
[17:17:30 INF] Invocation ID: 0b47e4f2-e98b-40fc-9253-276a71d65f73
[17:17:30 INF] Instance Name: default
[17:17:30 INF] Configuring application...
[17:17:30 INF] Using application directory /Users/aaron/Library/Application Support/slskd
[17:17:30 INF] Using configuration file /Users/aaron/Library/Application Support/slskd/slskd.yml
[17:17:30 INF] Storing application data in /Users/aaron/Library/Application Support/slskd/data
[17:17:31 INF] Listening for HTTP requests at http://0.0.0.0:5030/
[17:17:31 INF] Listening for HTTPS requests at https://0.0.0.0:5031/
[17:17:31 INF] Using randomly generated self-signed certificate
[17:17:31 FTL] Application terminated unexpectedly
Interop+AppleCrypto+AppleCommonCryptoCryptographicException: The specified item is no longer valid. It may have been deleted from the keychain.
   at Interop.AppleCrypto.X509CopyWithPrivateKey(SafeSecCertificateHandle certHandle, SafeSecKeyRefHandle privateKeyHandle, SafeKeychainHandle targetKeychain)
   at System.Security.Cryptography.X509Certificates.AppleCertificatePal.CopyWithPrivateKey(SafeSecKeyRefHandle privateKey)
   at System.Security.Cryptography.X509Certificates.AppleCertificatePal.CopyWithPrivateKey(RSA privateKey)
   at System.Security.Cryptography.X509Certificates.RSACertificateExtensions.CopyWithPrivateKey(X509Certificate2 certificate, RSA privateKey)
   at System.Security.Cryptography.X509Certificates.CertificateRequest.CreateSelfSigned(DateTimeOffset notBefore, DateTimeOffset notAfter)
   at slskd.Cryptography.X509.Generate(String subject, String password, X509KeyStorageFlags x509KeyStorageFlags)
   at slskd.Program.<>c.<Main>b__106_2(ListenOptions listenOptions)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.Listen(EndPoint endPoint, Action`1 configure)
   at slskd.Program.<>c.<Main>b__106_1(KestrelServerOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.CreateServiceContext(IOptions`1 options, ILoggerFactory loggerFactory, DiagnosticSource diagnosticSource, KestrelMetrics metrics)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl..ctor(IOptions`1 options, IEnumerable`1 transportFactories, IEnumerable`1 multiplexedFactories, IHttpsConfigurationService httpsConfigurationService, ILoggerFactory loggerFactory, KestrelMetrics metrics)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.WebApplication.get_ServerFeatures()
   at Microsoft.AspNetCore.Builder.WebApplication..ctor(IHost host)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   at slskd.Program.Main(String[] args)

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by jpdillingham** [comment]
Thanks for reporting this.  I know there were some security adjustments with this macOS update but am not yet aware of the details.

I did find [this article](https://dev.to/michaelcharles/fixing-the-https-developer-certificate-error-in-net-on-macos-sequoia-516h) which suggests the problem is with the logic that generates an X509 certificate, which certainly agrees with the stack trace here.

For context, slskd generates a self-signed X509 certificate on startup to enable https, and it does this by default if you don't supply your own certificate or disable HTTPS in the options.  You can read about how to disable HTTPS [here](https://github.com/slskd/slskd/blob/master/docs/config.md#https) and I'd appreciate if you'd try one of those methods and see if that gets you back up and running.

Alternatively you should be able to definitively rule in/out X509 generation by running `./slskd --generate-cert`, which essentially runs the X509 logic and nothing else.

In the meantime I will try and figure out how to enable X509 certificates with this new update.

**Comment by th3m4dt1t4n** [comment]
this is what I did and its working now, thanks for the help 
web:
   port: 5030
   https:
     disabled: true

**Comment by jpdillingham** [comment]
This is a confirmed issue with the .NET runtime: https://github.com/dotnet/announcements/issues/324

This should be fixed with the release of .NET 8.0.10 which is expected some time this month.  Releases can be monitored [here](https://dotnet.microsoft.com/en-us/download/dotnet/8.0); if this release becomes available and anybody notices it before I do, please ping me in this issue and I'll get a new build out.

**Comment by jpdillingham** [comment]
This should have been resolved some time in the last few months; .NET is up to 8.0.4x, and everything is pinned to .NET 8.0.x.  Feel free to reopen this if you're still having issues.
