### ISSUE TITLE
Stuck on glibc 2.24.

### ISSUE THREAD

**Issue by Soldenmerc** [slskd/slskd#1231]
I'm attempting to get slskd working on a machine I dont have sudo or root privilages on. It runs debian 9 stretch and the latest glib version is 2.24. 

This is the result when running the binary:
```
[19:47:23 INF] Version: 0.21.4.0 (0.21.4.0+a666532f)

[19:47:23 INF] System: .NET 8.0.8, Unix 6.1.44.0, 64 bit, 24 processors
[19:47:23 INF] Process ID: 3783943 (64 bit)
[19:47:23 INF] Invocation ID: a15ab0bb-0e80-4b8c-8857-0d18b500c229
[19:47:23 INF] Instance Name: default
[19:47:23 INF] Configuring application...
Unhandled exception. System.DllNotFoundException: Unable to load shared library                                           'e_sqlite3' or one of its dependencies. In order to help diagnose loading proble                                          ms, consider using a tool like strace. If you're using glibc, consider setting t                                          he LD_DEBUG environment variable:
/media/sdm1/skatz/.net/slskd/QERoYV6M7vqazbKXMwnKioQJp+oXZ6k=/e_sqlite3.so: cann                                          ot open shared object file: No such file or directory
/media/sdm1/skatz/bin/e_sqlite3.so: cannot open shared object file: No such file                                           or directory
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /me                                          dia/sdm1/skatz/.net/slskd/QERoYV6M7vqazbKXMwnKioQJp+oXZ6k=/libe_sqlite3.so)
/media/sdm1/skatz/bin/libe_sqlite3.so: cannot open shared object file: No such f                                          ile or directory
/media/sdm1/skatz/.net/slskd/QERoYV6M7vqazbKXMwnKioQJp+oXZ6k=/e_sqlite3: cannot                                           open shared object file: No such file or directory
/media/sdm1/skatz/bin/e_sqlite3: cannot open shared object file: No such file or                                           directory
/media/sdm1/skatz/.net/slskd/QERoYV6M7vqazbKXMwnKioQJp+oXZ6k=/libe_sqlite3: cann                                          ot open shared object file: No such file or directory
/media/sdm1/skatz/bin/libe_sqlite3: cannot open shared object file: No such file                                           or directory

   at SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_libversion_numbe                                          r()
   at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_lib                                          version_number()
   at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
   at SQLitePCL.Batteries_V2.Init()
   at SQLitePCL.Batteries.Init()
   at slskd.Program.InitSQLiteOrFailFast()
   at slskd.Program.Main(String[] args)
Aborted (core dumped)
```
Any ideas on how i could get this running? I tried the musl version but when executing ./slskd it prints "no such file or directory"

**Comment by jpdillingham** [comment]
SQLite is, unfortunately, a nightmare to try and bundle in a cross platform application, and this is why I have a function called `InitSQLiteOrFailFast()`; I think there are probably several dozen little configuration quirks that will cause it to malfunction and I'm not sure what they are exactly.

In this case the problem seems straightforward and I believe you've identified the root cause.  What I'm not sure of is which of the several SQLite meta packages I'll need to include to fix it, and whether doing so would break compatibility on some other system.

I'm spinning up a Debian 9 virtual machine to test whether adding a project reference to `SQLitePCLRaw.bundle_green` will fix it, as this is supposed to be the "batteries included" bundle.  I feel like I had this at one time and removed it, so I'll need to investigate that too.

If you want an immediate fix I think your only option is to use the Docker container.  If you're familiar with C# it would be helpful if you could add the `bundle_green` packages and build+test.

**Comment by jpdillingham** [comment]
Some background on the `bundle_green` package: https://github.com/ericsink/SQLitePCL.raw/discussions/429#discussioncomment-1063799 :\

I will do some more research into what's included in the Microsoft SQLite package

**Comment by jpdillingham** [comment]
@Soldenmerc here's a build with the bundle included: https://drive.google.com/file/d/1m_pB9ndZi2zQpvW5EqtB91PWDI8dAGsO/view?usp=drive_link

Please give it a try and see if it fixes the problem (I wasn't able to get my Debian VM up and running, all the repos are shut down etc)

**Comment by Soldenmerc** [comment]
> @Soldenmerc here's a build with the bundle included: https://drive.google.com/file/d/1m_pB9ndZi2zQpvW5EqtB91PWDI8dAGsO/view?usp=drive_link
> 
> Please give it a try and see if it fixes the problem (I wasn't able to get my Debian VM up and running, all the repos are shut down etc)
> 
> Note that I neglected to set the executable flag on `slskd` in the zip, once you unzip it run `chmod +x slskd` otherwise you'll get permission denied.
> 
> I tested this on a newer Ubuntu install and it works fine.

Just tested it and unfortunately:
```
[03:26:09 INF] Version: 0.21.4 (0.21.4+5f43e34e)
[03:26:09 INF] System: .NET 8.0.3, Unix 6.1.44.0, 64 bit, 24 processors
[03:26:09 INF] Process ID: 1421664 (64 bit)
[03:26:09 INF] Invocation ID: 8af01efd-e5d3-4a35-8082-d0b7670976cd
[03:26:09 INF] Instance Name: default
[03:26:09 INF] Configuring application...
Unhandled exception. System.DllNotFoundException: Unable to load shared library                        'e_sqlite3' or one of its dependencies. In order to help diagnose loading proble                       ms, consider using a tool like strace. If you're using glibc, consider setting t                       he LD_DEBUG environment variable:
/media/sdm1/skatz/.net/slskd/32ugWJNGPc7fbbeT53WMQ6+R1OrEBEw=/e_sqlite3.so: cann                       ot open shared object file: No such file or directory
/media/sdm1/skatz/bin/linux-x64/e_sqlite3.so: cannot open shared object file: No                        such file or directory
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /me                       dia/sdm1/skatz/.net/slskd/32ugWJNGPc7fbbeT53WMQ6+R1OrEBEw=/libe_sqlite3.so)
/media/sdm1/skatz/bin/linux-x64/libe_sqlite3.so: cannot open shared object file:                        No such file or directory
/media/sdm1/skatz/.net/slskd/32ugWJNGPc7fbbeT53WMQ6+R1OrEBEw=/e_sqlite3: cannot                        open shared object file: No such file or directory
/media/sdm1/skatz/bin/linux-x64/e_sqlite3: cannot open shared object file: No su                       ch file or directory
/media/sdm1/skatz/.net/slskd/32ugWJNGPc7fbbeT53WMQ6+R1OrEBEw=/libe_sqlite3: cann                       ot open shared object file: No such file or directory
/media/sdm1/skatz/bin/linux-x64/libe_sqlite3: cannot open shared object file: No                        such file or directory

   at SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_libversion_numbe                       r()
   at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_lib                       version_number()
   at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
   at SQLitePCL.Batteries_V2.Init()
   at SQLitePCL.Batteries.Init()
   at slskd.Program.InitSQLiteOrFailFast()
   at slskd.Program.Main(String[] args)
Aborted (core dumped)
```

**Comment by jpdillingham** [comment]
I wasn't able to make any progress, so I'm adding the `help wanted` tag in the hopes someone more familiar with SQLite binaries can chime in.

**Comment by mathiascode** [comment]
You either have to compile the SQLite binaries on earlier versions of distros that use an older glibc version, or upgrade your own distro. The former will likely be difficult, since such distros have reached EOL by now. Impossible if you use pre-compiled binaries.

Static linking would be the ideal option, but I doubt it's possible for this project.

**Comment by mathiascode** [comment]
Closing due to comment above.
