### ISSUE TITLE
Browse cache error on clean start

### ISSUE THREAD

**Issue by vitoyucepi** [slskd/slskd#1253]
## Summary

Sometimes during the clean startup I get the following error.
```
[10:28:15 INF] Browse response cached successfully in 106ms
[10:28:15 ERR] Error caching browse response: The process cannot access the file '/app/data/browse.cache' because it is being used by another process.
System.IO.IOException: The process cannot access the file '/app/data/browse.cache' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Int64& fileLength, UnixFileMode& filePermissions)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at slskd.Application.CacheBrowseResponse()
```

## Details

I don't know exactly how to reproduce the error, but I am using the following config
```yaml
services:
  slskd:
    image: slskd/slskd:latest
    restart: always
    environment:
      TZ: ${TZ}
      SLSKD_USERNAME: "test"
      SLSKD_PASSWORD: "test"
      SLSKD_NO_VERSION_CHECK: "true"
      SLSKD_NO_LOGO: "true"
    deploy:
      resources:
        limits:
          cpus: 0.3
```

## Versions

- slskd: 0.22.0

**Comment by jpdillingham** [comment]
Thanks for reporting this.  I'll take a look at the logic and try to figure out what might be opening the cache file before it is overwritten.

**Comment by ArgentumCation** [comment]
Has there been any progress with this? I'm seeing the same results on `0.24.0.0 (0.24.0.0+59e1cafa)`
```
[17:48:56 ERR] Error caching browse response: The process cannot access the file '/app/data/browse.cache' because it is being used by another process.
System.IO.IOException: The process cannot access the file '/app/data/browse.cache' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Int64& fileLength, UnixFileMode& filePermissions)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at slskd.Application.CacheBrowseResponse()
```
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: slskd
  name: slskd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slskd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: slskd
    spec:
      containers:
        - image: slskd/slskd
          name: slskd
          ports:
            - containerPort: 5030
              protocol: TCP
            - containerPort: 5031
              protocol: TCP
            - containerPort: 50300
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: slskd-config-volume
            - mountPath: /app/downloads
              name: slskd-downloads-volume
            - mountPath: /music
              name: slskd-music-volume
      restartPolicy: Always
      volumes:
        - name: slskd-config-volume 
          persistentVolumeClaim:
            claimName: slskd-config-pvc
        - name: slskd-downloads-volume
          persistentVolumeClaim:
            claimName: slskd-downloads-pvc 
        - name: slskd-music-volume 
          persistentVolumeClaim:
            claimName: slskd-music-pvc 
```
