### ISSUE TITLE
Frequent restarts, failing share scans and 'failed to execute shared file query' log entries.

### ISSUE THREAD

**Issue by pozineg** [slskd/slskd#1265]
Hi,

I'm getting loads of these log entries:

at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
at slskd.Shares.SqliteShareRepository.Search(SearchQuery query)
[slskd.Shares.SqliteShareRepository] [10:26:12 WRN] Failed to execute shared file query '3oh -bryan adams -from zero -housezzz -village people': SQLite Error 1: 'no such table: filenames'.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: filenames'.

...shortly after being connected to Soulseek server at:

2024-12-28T14:40:58.402735478Z [slskd.Application] [14:40:58 DBG] Excluded search phrases: bryan adams, from zero, housezzz, village people

...and I don't know how to get rid of it. No exclusion paths are configured in webui.

I may have excluded these phrases during initial signup and setup on SoulseekQT only Mac but since I run slaked on my NAS in docker I don't use SoulseekQT and I deleted it. But in order to check I brought it back, I've logged into it, checked settings, exclusions, shares not configured, folders not configured etc and everything is default, unconfigured apart from login details. Now disconnected from SoulseekQT and binned it.

I'm not sure if the above logs indicate db problem and are related to slskd acting up apart from being annoying.

Slskd webui often says: Lost connection to slskd. Refresh to reconnect. There are sometimes network RX spikes when slskd restarts and webui requires log in afterwards. Share autoscans always fail to complete around 76% at best with different memory/disk/workers configs and scanning shares only works when initiated manually in webui so    no_share_scan: true has to be active. I've tried clean installs, different configs, restarted NAS couple of times etc, but nothing helps.

I'm having a hard time getting to the bottom of this behaviour.

My share is not that big, around 220GB, 5800 files in 700 folders.

I'm running slskd as a docker container. Attaching:

Docker Compose.txt 
slskd.yml
shares.local.bak.db
slskd_logs.txt
slskd_logs_with _share _autoscan_enabled_and _failing.txt
SoulseekQT Config.scd1
System stats screenshot

Hope this would help to investigate.

Thanks

[Docker Compose.txt](https://github.com/user-attachments/files/18266669/Docker.Compose.txt)
[search.db.txt](https://github.com/user-attachments/files/18266670/search.db.txt)
[shares.local.bak.db.txt](https://github.com/user-attachments/files/18266671/shares.local.bak.db.txt)
[slskd_logs_with _share _autoscan_enabled_and _failing.txt](https://github.com/user-attachments/files/18266672/slskd_logs_with._share._autoscan_enabled_and._failing.txt)
[slskd_logs.txt](https://github.com/user-attachments/files/18266673/slskd_logs.txt)
[slskd.yml.txt](https://github.com/user-attachments/files/18266674/slskd.yml.txt)
[SoulseekQT Config.scd1.txt](https://github.com/user-attachments/files/18266675/SoulseekQT.Config.scd1.txt)
![System Stats](https://github.com/user-attachments/assets/859efe14-b717-4124-81c3-7c482a73dc1e)

**Comment by jpdillingham** [comment]
The `Failed to execute shared file query` error is related to the `no_share_scan` flag, though I'm not 100% certain of the timing and interactions.  The share scan needs to complete successfully at least once for all of the tables to exist.  I'll have to work on making that more obvious.

The added search phrases are dictated by the server, so nothing to worry about there.

The big mystery is why your share scan won't complete.  Looking at the timestamps I can see that it's moving about as fast as it does on my machine configured to point at my NAS, so nothing jumps out there.

Can you please do me a favor and set `shares.cache.workers` to 1 and see if that changes anything?

And can you also share more about your NAS? There's a known performance problem when the app runs on a copy-on-write filesystem such as BTRFS or ZFS ([details](https://github.com/slskd/slskd/blob/master/docs/known_issues.md#devices-using-a-copy-on-write-filesystem-such-as-btrfs-or-zfs)) and that may be causing an issue, but I think it's unlikely given the symptoms.

**Comment by pozineg** [comment]
Hi,
I'm running Docker on Synology Volume with Btrfs file system with 4GB memory  on board and managing it with Portainer. 

For these debugging sessions NAS has been restarted and steps taken are as follows (you've asked for it my dearvdev friend ;-):

Debug session #1:
1. slskd.yml modified to include verbose debugging log and db log, workers set to 1 with memory cash and repeated share caching enabled (slskd.yml. - debugging submission.txt attached).
2. Docker compose modified accordingly for a required startup settings (session 1 and 2 - docker compose - debugging submission.txt attached - modified for session #3 due to mistake with SLSKD_NO_SHARE_SCAN=true parameter).
3. slskd container was stopped and then removed including non-persistent volumes for a clean start and log file.
4. Running fresh slskd install with the above docker compose file at 16:34.
5. Ass soon as container started, log and system stats are being recorded (session 1 - system stats.png attached).
6. Portainer reports slskd container status: healthy.
7. Running slskd for 23 min.
8. As I couldn't see slskd running automated share scan in the log, I've stopped the container and started it the again at 16:57, manual scan on webui initiated at 17:01.
9. Scan with 1 worker engaged runs very slowly.
10. slskd restarted itself at 17:08 and I hadn't dump logs.
11. slskd resumed at 17:19, logs dumped at 17:27, webui shows completed share scan (session 1 - slskd_logs - after slskd restarted.txt attached).

Debug session #2 from pt #3 (different steps taken and behaviour detected):
3. slskd container was stopped and then removed including non-persistent volumes for a clean start and log file.
4. Running fresh slskd install with the above docker compose file at 17:32.
5. Ass soon as container started, log and system stats are being recorded (session 2 - system stats.png attached).
6. Portainer reports slskd container status: healthy.
7. As I couldn't see slskd running automated share scan in the log, I've initiated manual scan on webui at 17:41:17 without restarting the container this time.
8. Scan with 1 worker engaged runs very slowly.
9. Dumping logs at 17:44, as soon as scanning shares was showing in the log (session 2 - slskd_logs.txt attached).
10. webui disconnected around 17:51 and Portainer is reporting container status: unhealthy with CPU usage down to 0% and logs inaccessible. (session 2 - webui disconnected.png attached).
11. slskd is unresponsive.
12. I couldn't stop it or kill it, Docker on NAS had to be restarted :-(

At this point, after combing through log file it doesn't seem like share scan was being initiated at all. I might be missing something terribly though. Looking at the docker compose file I've noticed:
     - SLSKD_NO_SHARE_SCAN=true
changed to:
#      - SLSKD_NO_SHARE_SCAN=false and and left it hashed out in slskd.yml

Debug session #3 from pt #3 (fingers x all goes well):
3. slskd container was stopped and then removed including non-persistent volumes for a clean start and log file.
4. Running fresh slskd install with the modified docker compose file at 18:37 (session 3 - docker compose - debugging submission.txt attached).
5. Ass soon as container started log and system stats are being recorded.
6. Portainer reports slskd container status: healthy.
7. I dont't see slskd running share scan in the log, however for the first time share cache was loaded from disk and webui is showing share stats on the share tab where previously were "?" instead of numbers, before the manual scan was performed.
8. I've initiated manual scan on webui at 17:55:15.
9. This time, shared directories scan with 1 worker engaged runs even slower but at 31 % container is still healthy; I wonder if it completes the task or at what point terminates. Watching closely.
10. webui seems to be 1% ahead of the log records in shared directories scan %.
11. All back to normal.
12. 19:18:00 - so far so good, at 71% scan.
13. 19:19:40 lost connection to webui, not reconnecting, container status healthy, logging in progress, CPU down very low.
14. webui not reconnecting - white screen.
15. container back to healthy at 19:23:53.
16. webui trying to connect with intermittent blank/white screen at 71% scan in the log.
17. container status unhealthy at 19:26 for 2 mins.
18. webui back to normal showing 74% at 19:30:00 but log not updated still at 71%.
19. lost connection to webui around 19:31.
20. container status unhealthy at 19:32 for 1:30 mins.
21. webui back to normal showing 77% at 19:34:30.
22. 19:38:19 all good at 90% scan progress.
23. Scan completed, I will let it run for some time to see how it goes from now on.
24. webui keeps losing connection with back end, now and then.
25. All good at 20:35 log dumped and system stats recorded (session 3 - slskd_logs.txt divided to pt.1 and pt.2 due to a file size limit, and session 3 - system stats.png. attached).

Debug session #4 from pt #3:
Now I'm going back to:
1. 16 workers and directories specified in slskd.yml (slskd.yml. - original - debugging submission.txt attached),
2. docker compose with  SLSKD_FORCE_SHARE_SCAN=true activated for a change (session 4 - docker compose - original - debugging submission.txt attached)
3. slskd container was stopped and then removed including non-persistent volumes for a clean start and log file.
4. Running fresh slskd install with "session 4 - docker compose - original - debugging submission.txt" at 20:30:30.
5. Ass soon as container started, log and system stats are being recorded (session 4 - system stats.png attached).
6. Portainer reports slskd container status: healthy.
7. slskd completed share scan with 16 workers engaged very fast but webui was inaccessible, seems like web server kicks in upon completion of the scan.
8. now connected to webui that's showing numbers in the share tab stats, instead of "?" like before - with autoscan off.
9. All good at 21:00, log dumped and system stats recorded (session 4 - slskd_logs.txt and attached).
10. I can still see excluded search phrases, obviously, but slskd doesn't seem to be dwelling on it, like you said (but I want to find them, delete them and get this freaking bryan adams and co.).

I cannot get close to these excluded search phrases anywhere, like they were set up, bagged and drowned in the middle of the ocean (SoulseekQT Config.scd1.txt attached). On the other hand, like you said, once "back end initiated" share scan completed successfully, the tables were updated accordingly and acknowledged these phrases once and for all, despite the fact, I've managed to run the scan on webui succesfully.

Hope this helps with your project development and supporting files get downloaded with no issues (as I see some exclamation marks below),

Thank you

[session 1 - slskd_logs.txt](https://github.com/user-attachments/files/18271044/session.1.-.slskd_logs.txt)
![session 1 - system stats](https://github.com/user-attachments/assets/c57c640c-2033-4139-ac41-8a693573f142)
[session 1 and 2 - docker compose - debugging submission.txt](https://github.com/user-attachments/files/18271045/session.1.and.2.-.docker.compose.-.debugging.submission.txt)
[session 2 - slskd_logs.txt](https://github.com/user-attachments/files/18271046/session.2.-.slskd_logs.txt)
![session 2 - system stats](https://github.com/user-attachments/assets/4781656b-dbf2-4ff1-ab10-164d3b44d764)
![session 2 - webui disconnected](https://github.com/user-attachments/assets/b282f62a-7068-4ec7-81bb-735c2fd5aeff)
[session 3 - docker compose - debugging submission.txt](https://github.com/user-attachments/files/18271047/session.3.-.docker.compose.-.debugging.submission.txt)
![session 3 - system stats](https://github.com/user-attachments/assets/3bb80edf-cf1b-4a11-9f09-6f63eb606938)
[session 3 pt. 1 - slskd_logs.txt](https://github.com/user-attachments/files/18271048/session.3.pt.1.-.slskd_logs.txt)
[session 3 pt. 2 - slskd_logs.txt](https://github.com/user-attachments/files/18271050/session.3.pt.2.-.slskd_logs.txt)
[session 4 - docker compose - original - debugging submission.txt](https://github.com/user-attachments/files/18271051/session.4.-.docker.compose.-.original.-.debugging.submission.txt)
[session 4 - slskd_logs.txt](https://github.com/user-attachments/files/18271052/session.4.-.slskd_logs.txt)
[session 4 - slskd.yml. - original - debugging submission.txt](https://github.com/user-attachments/files/18271053/session.4.-.slskd.yml.-.original.-.debugging.submission.txt)
![session 4 - system stats](https://github.com/user-attachments/assets/61e1b461-5936-40ed-af37-83f830731b4f)
[slskd.yml. - debugging submission.txt](https://github.com/user-attachments/files/18271055/slskd.yml.-.debugging.submission.txt)
[SoulseekQT Config.scd1.txt](https://github.com/user-attachments/files/18271056/SoulseekQT.Config.scd1.txt)

**Comment by mathiascode** [comment]
Any difference with slskd 0.24.1? There were some fixes related to the databases.
