### ISSUE TITLE
Transient errors when sharing SQLite connections among different threads

### ISSUE THREAD

**Issue by jpdillingham** [slskd/slskd#178]
I noticed a couple of transient errors servicing search requests, for example:

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at Microsoft.Data.Sqlite.SqliteConnection.RemoveCommand(SqliteCommand command)
   at Microsoft.Data.Sqlite.SqliteCommand.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at slskd.SharedFileCache.SearchAsync(SearchQuery query) in C:\Users\JP.WHATNET\source\repos\slskd\src\slskd\Application\SharedFileCache.cs:line 331
```

Doing some research it seems that the guidance (ex, https://github.com/dotnet/efcore/issues/20651) is to ensure SQLite connections are not shared across threads, which the existing code is absolutely doing.

Options are to synchronize access to the existing connection, which would potentially create a bottleneck, to rewrite the code to create a new connection for each query, or to build an internal connection pool of some sort.

As a first step, share a sufficiently large number of files and benchmark query resolution times so we can get a feel for how much of a performance impact synchronizing the connection would introduce.

**Comment by jpdillingham** [comment]
With the code unchanged the average duration of a lookup with 50,000 shared files was 0 milliseconds, with the highest being the initial lookup which took 2ms.  With a `ReaderWriterLockSlim` synchronizing the entire body of the search lookup, the average duration remains 0ms.

A query that returned 1088 records took 3ms while synchronized.

While the impact is negligible, I am concerned that lower power devices will suffer.  I think I'll opt for a rewrite that creates new connections.

**Comment by jpdillingham** [comment]
There are rules about how in-memory connection strings need to be constructed so that they can be shared among connections: https://www.sqlite.org/inmemorydb.html

It looks like a string similar to `file:memdb1?mode=memory&cache=shared` should be used.  In this case it seems `memdb1` is the identifier, which will need to be somewhat unique to allow multiple tables to be swapped in and out during cache rebuilds.
