### ISSUE TITLE
Downloading file located in the root folder of a user share fails

### ISSUE THREAD

**Issue by mathiascode** [slskd/slskd#325]
If you attempt to download a file from the root folder of a user's share (e.g. `Music\file.mp3`, possible when sharing from Nicotine+ at least), the attempt fails.

```
[INF] Downloading 1 files from user abc123
[ERR] Failed to download file(s) from user abc123: String cannot be of zero length. (Parameter 'oldValue')
System.ArgumentException: String cannot be of zero length. (Parameter 'oldValue')
   at System.String.Replace(String oldValue, String newValue)
   at slskd.Extensions.ToLocalRelativeFilename(String remoteFilename)
   at slskd.Extensions.ToLocalFilename(String remoteFilename, String baseDirectory)
   at slskd.Transfers.API.TransfersController.GetLocalFileStream(String remoteFilename, String saveDirectory)
   at slskd.Transfers.API.TransfersController.Enqueue(String username, IEnumerable`1 requests)
```

**Comment by jpdillingham** [comment]
Thanks for reporting this, I'll take a look.

**Comment by jpdillingham** [comment]
Not sure how this fell of my radar, but I ran across it the other day.  It looks like it should be a simple fix once I set up a reproduction.

**Comment by jpdillingham** [comment]
@mathiascode if you're still able, I'd appreciate if you could check and see if this is resolved in the latest release (should be ready ~30 minutes from now)

**Comment by mathiascode** [comment]
I'll check once I'm back home in a few days.

**Comment by mathiascode** [comment]
Seems to work fine.
