### ISSUE TITLE
Recoverable crash when setting an invalid option

### ISSUE THREAD

**Issue by jpdillingham** [slskd/slskd#425]
Just got this while fiddling with transfer buffer sizes:

```
[] [07:58:00 WRN] Options (re)configuration rejected.
[] [07:58:00 WRN] Invalid configuration:
  Soulseek:
    Connection:
      Buffer:
        The field Transfer must be between 81920 and 2147483647.
[] [07:58:00 WRN] Options (re)configuration rejected.
[] [07:58:00 WRN] Invalid configuration:
  Soulseek:
    Connection:
      Buffer:
        The field Transfer must be between 81920 and 2147483647.
[] [07:58:01 WRN] Options (re)configuration rejected.
[] [07:58:01 WRN] Invalid configuration:
  Soulseek:
    Connection:
      Buffer:
        The field Transfer must be between 81920 and 2147483647.
[] [07:58:01 ERR] An unhandled exception has occurred while executing the request.
Microsoft.Extensions.Options.OptionsValidationException: A validation error has occurred.
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
   at slskd.Transfers.API.TransfersController..ctor(IOptionsSnapshot`1 options, ISoulseekClient soulseekClient, ITransferTracker tracker, IFTPService ftpClient) in C:\Users\~~~\source\repos\slskd\src\slskd\Transfers\API\Controllers\TransfersController.cs:line 60
   at lambda_method123(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at slskd.Startup.<>c.<<Configure>b__20_1>d.MoveNext() in C:\Users\~~~\source\repos\slskd\src\slskd\Startup.cs:line 305
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

The UI/APIs became unresponsive until I fixed the issue.

It looks like `OptionsFactory` doesn't retain the previous known good configuration if you give it an invalid config.  I'll have to find a way to prevent this or work around it.

**Comment by jpdillingham** [comment]
It does seem like I'll have to write a "last known good configuration" wrapper and use that, if I want that behavior.  I'm not sure it will be worth it, since I'll have to use that anywhere anything from the options pattern is used today.

When editing options from the UI the yaml is pre-validated before it is written to disk, so the only way someone could break the app in this way is if they are manually editing the yaml while the app is running.

**Comment by jpdillingham** [comment]
Another possibility is to write a new configuration provider that "fakes" this behavior.  It is possible to get the "raw" configuration with `Configuration.GetSection(Program.AppName)`; I could materialize that somehow, and then stash it and trigger a configuration update with it.

**Comment by jpdillingham** [comment]
Closing this because it's just unavoidable using the Microsoft-provided configuration primitives (with auto-reload, which is a necessity for UI reconfiguration to work)
