### ISSUE TITLE
Auto-joined rooms not showing as joined on the web interface

### ISSUE THREAD

**Issue by sammypanda** [slskd/slskd#525]
here are some rooms i auto-joined
![joined fems, joined lgbtq+, joined gay](https://user-images.githubusercontent.com/38725335/174919993-67f638c2-9040-460d-93f3-8d9475d81260.png)

and the interface after logging in on that same session
![no rooms to display](https://user-images.githubusercontent.com/38725335/174920066-44e0158a-b587-433b-98d5-d131979a2cd8.png)

it will allow me the UI option of joining the one that on the backend has already been joined
![dialogue for joining, searched fems, checked the fems room and join button goes green to show it can be joined](https://user-images.githubusercontent.com/38725335/174920243-ccf10480-4ec3-497b-93da-880685bdb204.png)

but when joining it hangs and errors out on the console and reports that it has already been joined
![[10:46:00 WRN] Failed to join room fems: The server didn't respond to the request to join chat room fems. This probably indicates that the room is already joined.
[10:46:00 ERR] An unhandled exception has occurred while executing the request.
Soulseek.NoResponseException: The server didn't respond to the request to join chat room fems. This probably indicates that the room is already joined.
   at Soulseek.SoulseekClient.JoinRoomInternalAsync(String roomName, Boolean isPrivate, CancellationToken cancellationToken)
   at slskd.Messaging.RoomService.JoinAsync(String roomName)
   at slskd.Messaging.API.RoomsController.JoinRoom(String roomName)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at slskd.HTMLInjectionMiddleware.InvokeAsync(HttpContext context)
   at slskd.HTMLRewriteMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
](https://user-images.githubusercontent.com/38725335/174920383-18fe4392-735a-46c5-8e67-e851ef0aa75b.png)

...it's possible that they may only show up after someone has sent a message? But I'm not sure.. either way it won't show up immediately and it will act as if the already joined chats can be joined

this isn't really a big deal i.m.o. but thought i should make this anyway :)

**Comment by jpdillingham** [comment]
Thanks for reporting this, it should be an easy fix.
