### ISSUE TITLE
Error resolving search response for query requested by with token: Input/output error

### ISSUE THREAD

**Issue by smithjd15** [slskd/slskd#556]
Non-docker slskd-0.16.6-linux-arm on raspian (raspberry pi 2 model b)

[11:19:10 INF] Version: 0.16.6.0 (0.16.6.0-71739c2)
[11:19:11 INF] Invocation ID: "cb9d5eed-ea64-4c54-b1cb-022cb28d4776"
[11:19:11 INF] Process ID: 13114
[11:19:11 INF] Instance Name: default
[11:19:11 INF] Using application directory /home/pi/.local/share/slskd
[11:19:11 INF] Using configuration file /home/pi/.local/share/slskd/slskd.yml
[11:19:22 INF] Using base url /
[11:19:22 INF] Serving static content from /home/pi/slskd-0.16.6-linux-arm/wwwroot
[11:19:27 INF] Listening for HTTP requests at http://0.0.0.0:5000/
[11:19:27 INF] Listening for HTTPS requests at https://0.0.0.0:5001/
[11:19:27 INF] Using randomly generated self-signed certificate
[11:19:30 INF] Configuring client
[11:19:30 INF] Client configured
[11:19:30 INF] Listening on port 50000
[11:19:30 INF] Checking GitHub Releases for latest version
[11:19:31 INF] Scanning shares
[11:19:31 INF] Sharing /home/pi/share as share
[11:19:32 INF] Connected to the Soulseek server
[11:19:34 INF] Version 0.16.6.0 is up to date.
[11:19:35 INF] Logged in to the Soulseek server as XX
[11:19:39 INF] Scanned 100% of shared directories.  Found 258 files so far.
[11:19:40 INF] Shares scanned successfully. Found 17 directories and 258 files in 9489.8184ms

This message appears in the logs for what looks like every search hit and I have been unsuccessful trying to get slskd to provide search results:

Error resolving search response for query XXXX requested by XX with token X: Input/output error

Web control seems to work OK, and results appear when running a search. The soulseek user and password was set from the commandline because it was reported invalid when set in the config file.

**Comment by jpdillingham** [comment]
Thanks for reporting this. I need to see the full stack trace to pinpoint the source of the error and start trying to reproduce the problem; could you please [enable debugging](https://github.com/slskd/slskd/blob/master/docs/config.md#development-flags) by setting `SLSKD_DEBUG=true` or running the app with `--debug`?

This will produce verbose logs, potentially including the names of shared files.  To protect your privacy make sure to sanitize logs before posting, or you can email them to logs@slskd.org.

**Comment by smithjd15** [comment]
[] [11:43:21 INF] Version: 0.16.6.0 (0.16.6.0-71739c2)
[] [11:43:21 INF] Invocation ID: "02f5fda6-6d27-4868-95e7-1bcdfefbb557"
[] [11:43:21 INF] Process ID: 13273
[] [11:43:21 INF] Instance Name: default
[] [11:43:21 INF] Using application directory /home/pi/.local/share/slskd
[] [11:43:21 INF] Using configuration file /home/pi/.local/share/slskd/slskd.yml
[] [11:43:23 DBG] Initializing database context SearchDbContext
[] [11:43:35 INF] Using base url /
[] [11:43:35 INF] Serving static content from /home/pi/slskd-0.16.6-linux-arm/wwwroot
[] [11:43:40 INF] Listening for HTTP requests at http://0.0.0.0:5000/
[] [11:43:40 INF] Listening for HTTPS requests at https://0.0.0.0:5001/
[] [11:43:40 INF] Using randomly generated self-signed certificate
[] [11:43:45 INF] Configuring client
[Soulseek.SoulseekClient] [11:43:45 DBG] Options reconfigured successfully
[] [11:43:45 INF] Client configured
[] [11:43:45 INF] Listening on port 50000
[] [11:43:45 INF] Checking GitHub Releases for latest version
[] [11:43:46 INF] Scanning shares
[] [11:43:46 DBG] Starting shared file scan
[] [11:43:46 DBG] {"id":"61F64AFC4346CFFB1ADE88D1EEA417726B4796BC","alias":"share","isExcluded":false,"localPath":"/home/pi/share","raw":"/home/pi/share","remotePath":"share"}
[] [11:43:46 INF] Sharing /home/pi/share as share
[] [11:43:46 DBG] Enumerating shared directories
[] [11:43:46 DBG] Found 17 shared directories (and 0 were excluded) in 173ms.  Starting file scan.
[] [11:43:47 INF] Connected to the Soulseek server
[] [11:43:51 INF] Version 0.16.6.0 is up to date.
[] [11:43:52 INF] Logged in to the Soulseek server as XX
[] [11:43:54 INF] Scanned 100% of shared directories.  Found 258 files so far.
[] [11:43:54 DBG] Directory scan found 258 files (and 0 were filtered) in 7931ms.  Populating filename database
[] [11:43:55 DBG] Inserted 258 records in 325ms
[] [11:43:55 INF] Shares scanned successfully. Found 17 directories and 258 files in 9530.2027ms
[] [11:43:55 DBG] Shared file cache recreated in 9151ms.  Directories: 17, Files: 258
[Soulseek.SearchResponder] [11:44:35 WRN] Error resolving search response for query XXXX requested by XX with token X: Input/output error

**Comment by jpdillingham** [comment]
Thanks for following up.  I'll try to set up a reproduction, but I'm pretty sure I have had it running outside of Docker on my RPI2 so may not get the result I'm looking for.

A couple of thoughts in the meantime:

* This could be missing dependencies.  You might try installing the ones listed here: https://github.com/slskd/slskd/issues/495#issuecomment-1149424889
* It could be permissions (but I highly doubt it since actual file I/O isn't executed in this path).  Try running as root (briefly) and see if that clears it up

**Comment by jpdillingham** [comment]
Also, (nearly forgot about this), enabling [Soulseek.NET diagnostics](https://github.com/slskd/slskd/blob/master/docs/config.md#diagnostic-level) might shed some more light on the issue.  I'll try to push a change tonight that will help uncover where the exception is being thrown.

**Comment by jpdillingham** [comment]
I released [0.16.7](https://github.com/slskd/slskd/releases/tag/0.16.7) last night, which includes changes to include the full error when this happens.  When you get a chance, please upgrade to this version and share the new exception message.

**Comment by smithjd15** [comment]
[Soulseek.SearchResponder] [10:13:02 WRN] Error resolving search response for query XXXX requested by XX with token X: Input/output error
[] [10:13:52 WRN] Failed to resolve search response: Input/output error
System.IO.IOException: Input/output error
   at System.ConsolePal.Write(SafeFileHandle fd, ReadOnlySpan`1 buffer, Boolean mayChangeCursorPosition)
   at System.ConsolePal.UnixConsoleStream.Write(ReadOnlySpan`1 buffer)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.WriteLine(String value)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
   at System.Console.WriteLine(String value)
   at slskd.Application.SearchResponseResolver(String username, Int32 token, SearchQuery query)

**Comment by jpdillingham** [comment]
How are you starting the app? This is an extremely rare exception that implies the app can't write to stdout for some reason.  This _might_ make sense if you're running it as a service or something, but I have no idea why other logs would work and not `Console.WriteLine()`

I'll release a new version this evening with all of the console writes removed in favor of using the logger (I should have done this a long time ago anyway) and hopefully that will fix it, but I'm very curious what's causing it.

**Comment by smithjd15** [comment]
Bash backgrounded with slskd &. Commandline options include soulseek user and password, share path, and debug info flags.

**Comment by jpdillingham** [comment]
Can you run the app with `--version` and report back whether it prints?

I'm working on putting a fresh install of raspbian on my RPI2 at the moment and am hopeful that I'll be able to reproduce this.

Regarding lack of diagnostics, the code reacts to incoming search requests and stops handling the request upon the first error, so this shouldn't be an indicator of anything.  It sounds like everything else is working, it just can't search the local share for files matching the request.

I'm fairly confident that this is really an issue with SQLite but am very confused about the actual exception.

**Comment by jpdillingham** [comment]
[0.16.8](https://github.com/slskd/slskd/releases/tag/0.16.8) is available now.  It should fix the immediate issue, but may uncover others.  Please give it a try when you have a minute.

**Comment by smithjd15** [comment]
`./slskd --version`
prints
`0.16.8.0 (0.16.8.0-e4644eb)`

I haven't tested my pi2 without debug output just to be sure, though it's so far still running with debug output. No sign of the error message.

Probably unrelated: I get an exception related to file uploads (on a pi4 this time). It's a file not found error, though the upload does complete.

[12:36:50 INF] [UPLOAD REQUESTED] X requested ss_share/XXXX]
[12:36:51 WRN] Failed to estimate place in queue for ss_share/XXXX requested by X
System.IO.FileNotFoundException: File ss_share/XXXX is not enqueued for user X
   at slskd.Transfers.UploadQueue.EstimatePosition(String username, String filename)
   at slskd.Application.PlaceInQueueResolver(String username, IPEndPoint endpoint, String filename)
   at Soulseek.Messaging.Handlers.PeerMessageHandler.TrySendPlaceInQueueAsync(IMessageConnection connection, String filename)
[12:36:51 WRN] Failed to resolve place in queue for file ss_share/XXXX from X: File ss_share/XXXX is not enqueued for user X
[12:36:51 INF] Added user X to watch list
[12:36:51 INF] [UPLOAD] [X/XXXX] None => Queued, Locally
[12:36:51 INF] [UPLOAD] [X/XXXX] Queued, Locally => Requested
[12:36:51 INF] [UPLOAD] [X/XXXX] Requested => Initializing
[12:36:52 INF] [UPLOAD] [X/XXXX] Initializing => InProgress
[12:37:48 INF] [UPLOAD] [X/XXXX] InProgress => Completed, Succeeded (37604440/37604440 = 100%) @ 653.7 KB/s

**Comment by smithjd15** [comment]
Looks fixed.

**Comment by jpdillingham** [comment]
Thanks for following up and confirming!

I think what was happening is that the app lost access to stdout due to being backgrounded.  I couldn't reproduce this so it must be something OS specific.
