### ISSUE TITLE
"database disk image is malformed" after container crash

### ISSUE THREAD

**Issue by AtActionPark** [slskd/slskd#634]
After a CPU spike, the container has become unresponsive ("tried to kill container, but did not receive an exit event") and I had to restart the docker service.

After restart, the containers does starts but stops after a "database disk image is malformed" error.

Is there something I can do other than deleting the db?

thanks

```
today at 4:51:38 PM[14:51:38 INF] Version: 0.16.21.0 (0.16.21.0-25191b8)
today at 4:51:38 PM[14:51:38 INF] Invocation ID: b0f1a5b0-ff2e-4cd6-a82a-26df756fe1cc
today at 4:51:38 PM[14:51:38 INF] Process ID: 1
today at 4:51:38 PM[14:51:38 INF] Instance Name: default
today at 4:51:38 PM[14:51:38 INF] Using application directory /app
today at 4:51:38 PM[14:51:38 INF] Using configuration file /app/slskd.yml
today at 4:51:46 PM[14:51:46 ERR] Failed executing DbCommand (36ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
today at 4:51:46 PMSELECT COUNT(*) FROM "sqlite_master" WHERE "type" = 'table' AND "rootpage" IS NOT NULL;
today at 4:51:47 PM[14:51:47 ERR] Failed to initialize database context SearchDbContext: $SQLite Error 11: 'database disk image is malformed'.
today at 4:51:47 PMMicrosoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
today at 4:51:47 PM   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
today at 4:51:47 PM   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
today at 4:51:47 PM   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
today at 4:51:47 PM   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
today at 4:51:47 PM   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
today at 4:51:47 PM   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
today at 4:51:47 PM   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteScalar()
today at 4:51:47 PM   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteScalar(RelationalCommandParameterObject parameterObject)
today at 4:51:47 PM   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.HasTables()
today at 4:51:47 PM   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
today at 4:51:47 PM   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
today at 4:51:47 PM   at lambda_method1(Closure , IServiceProvider , DbContextOptions`1 )
today at 4:51:47 PM   at Microsoft.EntityFrameworkCore.Internal.DbContextFactory`1.CreateDbContext()
today at 4:51:47 PM   at slskd.Program.AddDbContext[T](IServiceCollection services, String filename)
today at 4:51:47 PM[14:51:47 FTL] Application terminated unexpectedly
today at 4:51:47 PMMicrosoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
today at 4:51:47 PM   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
today at 4:51:47 PM   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
today at 4:51:47 PM   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
today at 4:51:47 PM   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
today at 4:51:47 PM   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
today at 4:51:47 PM   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
today at 4:51:47 PM   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteScalar()
today at 4:51:47 PM   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteScalar(RelationalCommandParameterObject parameterObject)
today at 4:51:47 PM   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.HasTables()
today at 4:51:47 PM   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
today at 4:51:47 PM   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
today at 4:51:47 PM   at lambda_method1(Closure , IServiceProvider , DbContextOptions`1 )
today at 4:51:47 PM   at Microsoft.EntityFrameworkCore.Internal.DbContextFactory`1.CreateDbContext()
today at 4:51:47 PM   at slskd.Program.AddDbContext[T](IServiceCollection services, String filename)
today at 4:51:47 PM   at slskd.Program.ConfigureDependencyInjectionContainer(IServiceCollection services)
today at 4:51:47 PM   at slskd.Program.Main(String[] args)
01/01/1970, 1:00 AM
today at 4:51:45 PM Container stopped
```

**Comment by AtActionPark** [comment]
> Are you sure you have enough space for the Database?

yep, app directory is on a disk with a few To free

**Comment by jpdillingham** [comment]
Unfortunately nothing can be done; that error is internal to SQLite and indicates that the file is indeed broken.

I'm doing some other work around backups, and can probably schedule a periodic backup of databases so that not everything is lost if this happens again.

**Comment by AtActionPark** [comment]
Alright, that's what I feared :)

Thanks anyway
