### ISSUE TITLE
An exception occurred in the database while saving changes for context type 'slskd.Transfers.TransfersDbContext'.

### ISSUE THREAD

**Issue by AtActionPark** [slskd/slskd#766]
Hi,

I'm using slskd via a docker compose stack on a raspberry.
I started getting some errors trying to download a file while the user was disconnecting. After that I got a bunch of `SQLite Error 1: 'cannot rollback - no transaction is active'`. errors

I restarted the container but it errors out and doesnt complete.

Log below. Any idea of what I could do to solve the issue?

cheers

```
[09:33:27 INF] Instance Name: default

[09:33:27 INF] Using application directory /app

[09:33:27 INF] Using configuration file /app/slskd.yml

[09:33:27 INF] Storing application data in /app/data

[09:33:34 INF] Listening for HTTP requests at http://0.0.0.0:5000/

[09:33:34 INF] Listening for HTTPS requests at https://0.0.0.0:5001/

[09:33:34 INF] Using randomly generated self-signed certificate

[09:33:38 INF] Using base url /

[09:33:38 INF] Serving static content from /slskd/wwwroot

[09:33:42 ERR] An error occurred using a transaction.

[09:33:43 ERR] An exception occurred in the database while saving changes for context type 'slskd.Transfers.TransfersDbContext'.

Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'cannot rollback - no transaction is active'.

   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)

   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()

   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)

   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()

   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()

   at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText, SqliteParameter[] parameters)

   at Microsoft.Data.Sqlite.SqliteTransaction.RollbackInternal()

   at Microsoft.Data.Sqlite.SqliteTransaction.Dispose(Boolean disposing)

   at System.Data.Common.DbTransaction.Dispose()

   at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.Dispose()

   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)

   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__104_0(DbContext _, ValueTuple`2 t)

   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)

   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)

Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'cannot rollback - no transaction is active'.

   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)

   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()

   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)

   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()

   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()

   at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText, SqliteParameter[] parameters)

   at Microsoft.Data.Sqlite.SqliteTransaction.RollbackInternal()

   at Microsoft.Data.Sqlite.SqliteTransaction.Dispose(Boolean disposing)

   at System.Data.Common.DbTransaction.Dispose()

   at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.Dispose()

   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)

   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__104_0(DbContext _, ValueTuple`2 t)

   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)

   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)

[09:33:43 FTL] Application terminated unexpectedly

Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'cannot rollback - no transaction is active'.

   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)

   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()

   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)

   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()

   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()

   at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText, SqliteParameter[] parameters)

   at Microsoft.Data.Sqlite.SqliteTransaction.RollbackInternal()

   at Microsoft.Data.Sqlite.SqliteTransaction.Dispose(Boolean disposing)

   at Microsoft.Data.Sqlite.SqliteConnection.Close()

   at Microsoft.Data.Sqlite.SqliteConnection.Dispose(Boolean disposing)

   at System.ComponentModel.Component.Dispose()

   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.DisposeDbConnection()

   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.ResetState(Boolean disposeDbConnection)

   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Dispose()

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()

   at Microsoft.EntityFrameworkCore.DbContext.Dispose()

   at slskd.Transfers.Downloads.DownloadService.Update(Transfer transfer)

   at slskd.Application.Microsoft.Extensions.Hosting.IHostedService.StartAsync(CancellationToken cancellationToken)

   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)

   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)

   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)

   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)

   at Microsoft.AspNetCore.Builder.WebApplication.Run(String url)

   at slskd.Program.Main(String[] args)
```

**Comment by jpdillingham** [comment]
Thanks for reporting this.  Can you double check that you have free space on your disk?

**Comment by AtActionPark** [comment]
Yes, the app data folder is mounted on a partition with a few To of space left

**Comment by jpdillingham** [comment]
There's logic that cleans up transfers that were in progress at the last shutdown and it seems like the database is in a state that's causing issues.

Can you send your `transfers.db` file to logs@slskd.org? I should be able to reproduce this on my end.

**Comment by AtActionPark** [comment]
Issue fixed itself after restarting some other containers that were using the partition slskd db was present on. 
Sorry about that, I'll close the issue

thanks :)

**Comment by jpdillingham** [comment]
Thanks for following up!  I can't think of a reason that would cause this, but I'm learning that SQLite is quirky.

I've created #767 to hopefully make the experience less confusing.

This specific error (regarding transactions) is caused by Entity Framework, which I'm finding doesn't work well with SQLite, and I've considered ripping it out more than once now.  I'd encourage anyone that stumbles upon this issue to add a comment or create a new issue if they are experiencing similar problems.
