### ISSUE TITLE
Duplicate Downloads when attempting to retry errored downloads

### ISSUE THREAD

**Issue by technerdist** [slskd/slskd#966]
When clicking retry all on errored downloads, duplicates often populate. Even when one of the tracks with duplicates downloads, duplicates remain, showing error status. Removing an album with these duplicates takes multiple rounds of selecting all and removing before they'll clear. I can send a screenshot if you're curious.

**Comment by jpdillingham** [comment]
Thanks for reporting this.

I just tried to reproduce it with three and it worked as expected.  Approximately how many files are being retried when this happen? And how many are duplicated?

**Comment by WRMSRwasTaken** [comment]
I was able to see this happen when slskd complains about a locked sqlite db when trying to download a large folder from remotes, for me this was around 1000 files.

```
Oct 29 14:48:24 dl-vpn slskd[124]: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 6: 'database table is locked'.
Oct 29 14:48:24 dl-vpn slskd[124]:    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
Oct 29 14:48:24 dl-vpn slskd[124]:    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
Oct 29 14:48:24 dl-vpn slskd[124]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
Oct 29 14:48:24 dl-vpn slskd[124]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
Oct 29 14:48:24 dl-vpn slskd[124]:    at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText, SqliteParameter[] parameters)
Oct 29 14:48:24 dl-vpn slskd[124]:    at Microsoft.Data.Sqlite.SqliteTransaction..ctor(SqliteConnection connection, IsolationLevel isolationLevel, Boolean deferred)
Oct 29 14:48:24 dl-vpn slskd[124]:    at Microsoft.Data.Sqlite.SqliteConnection.BeginTransaction(IsolationLevel isolationLevel, Boolean deferred)
```

I think it would be better to have some local queuing system instead of trying to queue all files I'd want to download from a remote and then most of them erroring with "too many files" because the remote queue got too big.

**Comment by jpdillingham** [comment]
@WRMSRwasTaken does the `database table is locked` message go away on its own, or do you have to restart to clear it?

> I think it would be better to have some local queuing system instead of trying to queue all files I'd want to download from a remote and then most of them erroring with "too many files" because the remote queue got too big.

I have been thinking the same lately, but more in relation to the user experience when enqueuing the files initially.  It's pretty much the same mechanism under the hood, and I'm pretty sure the record is added to the database before the remote connection is made anyway.

I think this ties in to automated retries conceptually and I've been putting that off a while due to the complexity; the application doesn't have a way to do async work right now, outside of a rudimentary timer-based system.  This is basically #107 and #389.  I may make an attempt to get this done while I'm off for the holidays this week.

**Comment by awsms** [comment]
> I was able to see this happen when slskd complains about a locked sqlite db when trying to download a large folder from remotes, for me this was around 1000 files and then clicking retry on files failing to DL because the remote rejected it.
> 
> ```
> Oct 29 14:48:24 dl-vpn slskd[124]: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 6: 'database table is locked'.
> Oct 29 14:48:24 dl-vpn slskd[124]:    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
> Oct 29 14:48:24 dl-vpn slskd[124]:    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
> Oct 29 14:48:24 dl-vpn slskd[124]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
> Oct 29 14:48:24 dl-vpn slskd[124]:    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
> Oct 29 14:48:24 dl-vpn slskd[124]:    at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText, SqliteParameter[] parameters)
> Oct 29 14:48:24 dl-vpn slskd[124]:    at Microsoft.Data.Sqlite.SqliteTransaction..ctor(SqliteConnection connection, IsolationLevel isolationLevel, Boolean deferred)
> Oct 29 14:48:24 dl-vpn slskd[124]:    at Microsoft.Data.Sqlite.SqliteConnection.BeginTransaction(IsolationLevel isolationLevel, Boolean deferred)
> ```
> 
> I think it would be better to have some local queuing system instead of trying to queue all files I'd want to download from a remote and then most of them erroring with "too many files" because the remote queue got too big.

Getting the same issue when people download from my shares, slskd has basically become unusable for me :(

**Comment by jpdillingham** [comment]
@awsms did this start after a recent update? Roughly how many files are you sharing, how many people are downloading how many tracks?

**Comment by awsms** [comment]
> @awsms did this start after a recent update? Roughly how many files are you sharing, how many people are downloading how many tracks?

I'm sharing several TB of data. I don't remember when it started, all I can say is slskd doesn't work anymore for me (I'm able to log in, browse the UI for a couple of sec, then it freezes). Note that slskd never crashes, it only becomes unresponsive (forever).
That's basically what my terminal looks like when I run it:

```
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 6: 'database table is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText, SqliteParameter[] parameters)
   at Microsoft.Data.Sqlite.SqliteTransaction..ctor(SqliteConnection connection, IsolationLevel isolationLevel, Boolean deferred)
   at Microsoft.Data.Sqlite.SqliteConnection.BeginTransaction(IsolationLevel isolationLevel, Boolean deferred)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransaction(IsolationLevel isolationLevel)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
```

```
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 6: 'database table is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at slskd.Transfers.Uploads.UploadService.Update(Transfer transfer)
   at slskd.Transfers.Uploads.UploadService.<>c__DisplayClass37_1.<EnqueueAsync>g__SynchronizedUpdate|3(Transfer transfer, Boolean cancellable)
   at slskd.Transfers.Uploads.UploadService.<>c__DisplayClass37_2.<EnqueueAsync>b__10()
   at slskd.RateLimiter.Invoke(Action action)
   at slskd.Transfers.Uploads.UploadService.<>c__DisplayClass37_1.<EnqueueAsync>b__6(ValueTuple`2 args)
   at Soulseek.SoulseekClient.<>c__DisplayClass360_0.<UploadFromStreamAsync>g__UpdateProgress|1(Int64 bytesUploaded)
   at Soulseek.SoulseekClient.UploadFromStreamAsync(String username, String remoteFilename, Int64 size, Func`2 inputStreamFactory, Int32 token, TransferOptions options, CancellationToken cancellationToken)
   at slskd.Transfers.Uploads.UploadService.<>c__DisplayClass37_0.<<EnqueueAsync>b__2>d.MoveNext()
   ```
   
   ```
   [22:53:20 ERR] Failed executing DbCommand (35,487ms) [Parameters=[@p15='?' (DbType = Guid), @p0='?' (DbType = Double), @p1='?' (DbType = Int64), @p2='?' (Size = 6), @p3='?' (DbType = DateTime), @p4='?' (DbType = DateTime), @p5='?' (Size = 87), @p6='?' (Size = 58), @p7='?' (DbType = Int32), @p8='?' (DbType = Boolean), @p9='?' (DbType = DateTime), @p10='?' (DbType = Int64), @p11='?' (DbType = Int64), @p12='?' (DbType = DateTime), @p13='?' (Size = 18), @p14='?' (Size = 6)], CommandType='Text', CommandTimeout='30']
UPDATE "Transfers" SET "AverageSpeed" = @p0, "BytesTransferred" = @p1, "Direction" = @p2, "EndedAt" = @p3, "EnqueuedAt" = @p4, "Exception" = @p5, "Filename" = @p6, "PlaceInQueue" = @p7, "Removed" = @p8, "RequestedAt" = @p9, "Size" = @p10, "StartOffset" = @p11, "StartedAt" = @p12, "State" = @p13, "Username" = @p14
WHERE "Id" = @p15
RETURNING 1;
[22:53:20 ERR] An exception occurred in the database while saving changes for context type 'slskd.Transfers.TransfersDbContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 6: 'database table is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
```

**Comment by WRMSRwasTaken** [comment]
My slskd became practically unusable, the web GUI only prints "Lost connection to slskd  Retrying..." and slskd is pegging 1 CPU thread at 100%, sporadically logging `SQLite Error 6: 'database table is locked: Transfers'.`

Seems as I have to completely remove the SQLite file to get it up and running again. Might try to see what it's giving me on debug output later / the next days...

**Comment by bugmancx** [comment]
I don't know how to trigger this to occur to begin with, but I get this as well. It seems to happen whenever "Retry all errored" kicks in.  I get the error message:

```
[slskd.Transfers.Downloads.DownloadService] [15:00:55 ERR] Download of path\to\file.mp3 from user theremoteuser failed: An active or queued download of path\to\file.mp3 from theremoteuser is already in progress
Soulseek.DuplicateTransferException: An active or queued download of path\to\file.mp3 from theremoteuser is already in progress
   at Soulseek.SoulseekClient.DownloadAsync(String username, String remoteFilename, Func`1 outputStreamFactory, Nullable`1 size, Int64 startOffset, Nullable`1 token, TransferOptions options, Nullable`1 cancellationToken)
   at slskd.Transfers.Downloads.DownloadService.<>c__DisplayClass26_2.<<EnqueueAsync>b__1>d.MoveNext()
```
   
It will then add a new row to the database which contains a duplicate for this file. The duplicates can be seen via the database:
```

sqlite> SELECT * FROM Transfers WHERE Filename LIKE '%file%';
1447C2E7-A2AF-4CB5-AD35-8956941AAAAF|theremoteuser|Download|path\to\file.mp3|10375265|0|Completed, Errored|2024-10-11 13:25:41.0123929|||2024-10-11 13:25:43.95663|0|0.0||Transfer rejected: Too many megabytes|1
57979128-99BC-414F-988B-090D04E1C8E2|theremoteuser|Download|path\to\file.mp3|10375265|0|Completed, Errored|2024-10-11 13:51:10.737804|||2024-10-11 13:51:12.7044211|0|0.0||Transfer rejected: Too many megabytes|1
E7A7F5AC-AFC4-4366-95EA-4EF474EB9EDA|theremoteuser|Download|path\to\file.mp3|10375265|0|Completed, Errored|2024-10-11 13:52:37.1798816|||2024-10-11 13:52:37.4546903|0|0.0||Transfer rejected: Too many megabytes|1
23EFD9AC-2F41-4BDA-8958-312D101CB31A|theremoteuser|Download|path\to\file.mp3|10375265|0|Completed, Errored|2024-10-11 13:52:39.186077|||2024-10-11 13:52:39.4462797|0|0.0||Transfer rejected: Too many megabytes|1
FC17DAC9-945E-4889-A2B1-D52956236A57|theremoteuser|Download|path\to\file.mp3|10375265|0|Completed, Errored|2024-10-11 13:52:41.1966154|||2024-10-11 13:52:41.4519238|0|0.0||Transfer rejected: Too many megabytes|1
```

The end result is that each time the download is duplicated, it will remain in an errored state because it is already enqueued at the remote end, and an additional entry gets added to the database, compounding the issue.

If the duplicated file is successfully downloaded, the duplicates will continue if they are retried and the file requested is not already queued at their end. When you click the checkbox next to one of the duplicates, all of the duplicates select, so it is difficult to remove the dupes.

**Comment by jpdillingham** [comment]
Should be fixed in 0.24.0
