### ISSUE TITLE
Timeout exception when searching for some users (5000 millisecond)

### ISSUE THREAD

**Issue by sammypanda** [slskd/slskd#988]
I'm not sure what condition determines whether i can find a user or not, but some users will consistently exceed the timeout time. **I searched for a config option for this timeout but i couldn't find it**: So i'm not sure if it's just my internet/device is slow or if it's an actual issue. (ARM64, Raspberry Pi)

```
[10:21:15 ERR] An unhandled exception has occurred while executing the request.
System.TimeoutException: The wait timed out after 5000 milliseconds
   at Soulseek.SoulseekClient.GetUserInfoInternalAsync(String username, CancellationToken cancellationToken)
   at slskd.Users.UserService.GetInfoAsync(String username)
   at slskd.Users.API.UsersController.Info(String username)
   ...
   ```

**Comment by sammypanda** [comment]
oh i see where it is now, thank you @jpdillingham!
