### ISSUE TITLE
slskd within a Linux network namespace unable to upload

### ISSUE THREAD

**Issue by m999-9** [slskd/slskd#989]
Hello,

This is my first attempt at running `slskd`. I am running it within a Linux network namespace. A port is forwarded, configured in the client and has been successfully tested to be open. I am able to connect to the soulseek network, login, search, and send private messages.

Using a separate client on a different network, I am able to browse the files shared by `slskd` however none of the requested files are downloaded successfully, with an exception printed:

```
[21:57:21 ERR] Upload of [...] to user [...] failed: Failed to upload file [...] to user [...]: Transfer failed: Read error: Unable to read data from the transport connection: Connection reset by peer.
Soulseek.SoulseekClientException: Failed to upload file [...] to user [...]: Transfer failed: Read error: Unable to read data from the transport connection: Connection reset by peer.
 ---> Soulseek.ConnectionException: Transfer failed: Read error: Unable to read data from the transport connection: Connection reset by peer.
 ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at Soulseek.Network.Tcp.Connection.ReadInternalAsync(Int64 length, Stream outputStream, Func`3 governor, Action`3 reporter, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Soulseek.SoulseekClient.UploadFromStreamAsync(String username, String remoteFilename, Int64 size, Func`2 inputStreamFactory, Int32 token, TransferOptions options, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Soulseek.SoulseekClient.UploadFromStreamAsync(String username, String remoteFilename, Int64 size, Func`2 inputStreamFactory, Int32 token, TransferOptions options, CancellationToken cancellationToken)
   at Soulseek.SoulseekClient.UploadFromStreamAsync(String username, String remoteFilename, Int64 size, Func`2 inputStreamFactory, Int32 token, TransferOptions options, CancellationToken cancellationToken)
   at slskd.Transfers.Uploads.UploadService.<>c__DisplayClass37_0.<<EnqueueAsync>b__2>d.MoveNext()
```

Any idea what the issue may be?

Thank you.

**Comment by jpdillingham** [comment]
This is beyond my expertise with Linux networking so I would have to defer to others on what factors may be at play at the TCP level.

From an application perspective this would indicate that the connection was established successfully, which is the usual mode of failure if there's a networking issue.  In this case one or both of the clients has port forwarding configured correctly; you may want to disable forwarding on the second client to see which client accepted the connection.

You can set the [Soulseek diagnostic level](https://github.com/slskd/slskd/blob/master/docs/config.md#diagnostic-level) to `Debug` and enable slskd's [debug](https://github.com/slskd/slskd/blob/master/docs/config.md#development-flags) mode to get more insight into the connection negotiation process.  I'd be curious to see what those logs are if you'd like to share them, either here or via an email to logs@slskd.org (if you don't feel like scrubbing every line and trust me with the data)

There's an extremely outside chance that the negotiation process is malfunctioning and selecting the wrong connection, but I'd expect that to surface as a timeout and not a reset.  Disabling port forwarding on the second client will rule this out, too.

**Comment by Fran314** [comment]
Anyone found a solution for this? I am stumbling in the exact same issue: I can connect, log, search, send private messages but upon trying to upload a file I get the same stacktrace

**Comment by hanspaerna** [comment]
@Fran314 I have the same problem. Using slskd in Docker paired with gluetun and ProtonVPN and port forwarding turned on.

**Comment by jpdillingham** [comment]
Closing this because it is a configuration issue and not a problem with the application itself

**Comment by CornDrink** [comment]
@jpdillingham  What's the configuration issue? This is happening to me too

**Comment by jpdillingham** [comment]
It's not something that is related to slskd configuration, but rather the hosting environment/configuration.  The fact that the connection is "reset by peer" means the issue is somewhere between slskd and the other client, in the OS TCP stack, network, other person's client etc.  Not really anything I can fix or help troubleshoot.

Someone on reddit reported this same problem using ProtonVPN, and was able to fix it by turning off their "VPN Accelerator": https://www.reddit.com/r/Soulseek/comments/1sat3dz/slskd_protonvpn_users_can_browse_profile_files/

**Comment by N064** [comment]
> Someone on reddit reported this same problem using ProtonVPN, and was able to fix it by turning off their "VPN Accelerator": https://www.reddit.com/r/Soulseek/comments/1sat3dz/slskd_protonvpn_users_can_browse_profile_files/

Can confirm. In my case the problem was in "VPN Accelerator".

**Comment by CornDrink** [comment]
Unfortunately for me, VPN Accelerator has no impact. I've tried every combination of VPN options and I'm still getting errors when trying to upload. I'll just try again some other time.

**Comment by N064** [comment]
> Unfortunately for me, VPN Accelerator has no impact. I've tried every combination of VPN options and I'm still getting errors when trying to upload. I'll just try again some other time.

@CornDrink I can share my config. Maybe it will help.

WireGuard config:

```sh
# NetShield = 0
# Moderate NAT = on
# NAT-PMP (Port Forwarding) = on
# VPN Accelerator = off
```

Connect to VPN:

```sh
docker run -d \
  --name=vpn_client \
  --cap-add=NET_ADMIN \
  --device=/dev/net/tun:/dev/net/tun \
  -v /tmp/gluetun:/tmp/gluetun \
  -p 127.0.0.1:5030:5030 \
  -e VPN_SERVICE_PROVIDER=protonvpn \
  -e VPN_TYPE=wireguard \
  -e VPN_PORT_FORWARDING=on \
  -e VPN_PORT_FORWARDING_PROVIDER=protonvpn \
  -e PORT_FORWARD_ONLY=on \
  -e SERVER_COUNTRIES="Switzerland" \
  -e WIREGUARD_PRIVATE_KEY=YOUR_PRIVATE_KEY \
  --restart always \
  qmcgaw/gluetun
```

`SERVER_COUNTRIES` - important for stable connection.

Run `slskd`:

```sh
docker run -d \
  --name slskd \
  -v /app/slskd:/app \
  --network=container:vpn_client \
  slskd/slskd:latest
```

And update `listen_port` to value from `/tmp/gluetun/forwarded_port`.
