### ISSUE TITLE
Failed to retrieve latest release version from GitHub: Response status code does not indicate success: 403

### ISSUE THREAD

**Issue by mikew** [slskd/slskd#995]
My slskd container isn't able to come up, giving the error in the title:

```
soulseek-soulseek-1  |
soulseek-soulseek-1  |
soulseek-soulseek-1  |                      ▄▄▄▄     ▄▄▄▄     ▄▄▄▄
soulseek-soulseek-1  |                ▄▄▄▄▄▄█  █▄▄▄▄▄█  █▄▄▄▄▄█  █
soulseek-soulseek-1  |                █__ --█  █__ --█    ◄█  -  █
soulseek-soulseek-1  |                █▄▄▄▄▄█▄▄█▄▄▄▄▄█▄▄█▄▄█▄▄▄▄▄█
soulseek-soulseek-1  | ╒════════════════════════════════════════════════════════╕
soulseek-soulseek-1  | │           GNU AFFERO GENERAL PUBLIC LICENSE            │
soulseek-soulseek-1  | │                   https://slskd.org                    │
soulseek-soulseek-1  | │                                                        │
soulseek-soulseek-1  | │              0.19.1.0 (0.19.1.0+8438098e)              │
soulseek-soulseek-1  | └────────────────────────────────────────────────────────┘
soulseek-soulseek-1  | [19:55:47 INF] Version: 0.19.1.0 (0.19.1.0+8438098e)
soulseek-soulseek-1  | [19:55:47 INF] System: .NET 7.0.13, Unix 6.2.6.1, 64 bit, 8 processors
soulseek-soulseek-1  | [19:55:47 INF] Process ID: 7 (64 bit)
soulseek-soulseek-1  | [19:55:47 INF] Invocation ID: 5341f8f2-d890-4fb4-95ba-0f6a1ee0de14
soulseek-soulseek-1  | [19:55:47 INF] Instance Name: default
soulseek-soulseek-1  | [19:55:47 INF] Configuring application...
soulseek-soulseek-1  | [19:55:47 INF] Using application directory /app
soulseek-soulseek-1  | [19:55:47 INF] Using configuration file /app/slskd.yml
soulseek-soulseek-1  | [19:55:47 INF] Storing application data in /app/data
soulseek-soulseek-1  | [19:55:47 INF] Listening for HTTP requests at http://0.0.0.0:5030/
soulseek-soulseek-1  | [19:55:47 INF] Using base url /
soulseek-soulseek-1  | [19:55:47 INF] Serving static content from /slskd/wwwroot
soulseek-soulseek-1  | [19:55:48 INF] Configuration complete.  Starting application...
soulseek-soulseek-1  | [19:55:48 INF] Application started
soulseek-soulseek-1  | [19:55:48 INF] Listening for incoming connections on port 50300
soulseek-soulseek-1  | [19:55:48 INF] Checking GitHub Releases for latest version
soulseek-soulseek-1  | [19:55:48 INF] Initializing shares
soulseek-soulseek-1  | [19:55:48 INF] Share cache StorageMode is 'Disk'. Attempting to validate...
soulseek-soulseek-1  | [19:55:48 INF] Share cache loaded from disk successfully. Sharing 69 directories and 158 files
soulseek-soulseek-1  | [19:55:48 INF] Warming browse response cache...
soulseek-soulseek-1  | [19:55:48 INF] Browse response cached successfully in 50ms
soulseek-soulseek-1  | [19:55:48 WRN] Failed to check version: Failed to retrieve latest release version from GitHub: Response status code does not indicate success: 403 (rate limit exceeded).
soulseek-soulseek-1  | [19:55:48 FTL] Application terminated unexpectedly
soulseek-soulseek-1  | Soulseek.AddressException: Failed to resolve address '': Resource temporarily unavailable
soulseek-soulseek-1  |  ---> System.Net.Sockets.SocketException (00000001, 11): Resource temporarily unavailable
soulseek-soulseek-1  |    at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, Int64 startingTimestamp)
soulseek-soulseek-1  |    at System.Net.Dns.GetHostEntry(String hostNameOrAddress, AddressFamily family)
soulseek-soulseek-1  |    at Soulseek.SoulseekClient.ConnectAsync(String address, Int32 port, String username, String password, Nullable`1 cancellationToken)
soulseek-soulseek-1  |    --- End of inner exception stack trace ---
soulseek-soulseek-1  |    at Soulseek.SoulseekClient.ConnectAsync(String address, Int32 port, String username, String password, Nullable`1 cancellationToken)
soulseek-soulseek-1  |    at Soulseek.SoulseekClient.ConnectAsync(String username, String password, Nullable`1 cancellationToken)
soulseek-soulseek-1  |    at slskd.Application.Microsoft.Extensions.Hosting.IHostedService.StartAsync(CancellationToken cancellationToken)
soulseek-soulseek-1  |    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
soulseek-soulseek-1  |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
soulseek-soulseek-1  |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
soulseek-soulseek-1  |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
soulseek-soulseek-1  |    at slskd.Program.Main(String[] args)
soulseek-soulseek-1 exited with code 0
```

Here's my docker-compose.yml:

```yml
version: '2'

services:
  soulseek:
    image: slskd/slskd
    networks:
      - default
      - reverse-proxy
    user: ${HOMELAB_USER_ID}:${HOMELAB_GROUP_ID}
    env_file: env
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_DOWNLOADS_DIR=/storage/torrents-complete
      - SLSKD_INCOMPLETE_DIR=/storage/torrents-complete
      - SLSKD_SHARED_DIR=/storage/torrents-complete
      - SLSKD_SHARE_CACHE_STORAGE_MODE=disk
      - SLSKD_NO_HTTPS=true
      #- SLSKD_NO_VERSION_CHECK=true
    ports:
      - 50300:50300
    volumes:
      - ./persistent/slskd:/app
      - ${HOMELAB_STORAGE_PATH}:/storage
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-soulseek.rule=Host(`soulseek.${HOMELAB_BASE_DOMAIN}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-soulseek.entrypoints=web,websecure
      - traefik.http.services.${COMPOSE_PROJECT_NAME}-soulseek.loadbalancer.server.port=5030

networks:
  reverse-proxy:
    external: true
```

And when I use that `SLSKD_NO_VERSION_CHECK=true` environment variable, it's still not able to come up (with a different error at least):

```
soulseek-soulseek-1  |
soulseek-soulseek-1  |
soulseek-soulseek-1  |                    ▄▄▄▄         ▄▄▄▄       ▄▄▄▄
soulseek-soulseek-1  |            ▄▄▄▄▄▄▄ █  █ ▄▄▄▄▄▄▄ █  █▄▄▄ ▄▄▄█  █
soulseek-soulseek-1  |            █__ --█ █  █ █__ --█ █    ◄█ █  -  █
soulseek-soulseek-1  |            █▄▄▄▄▄█ █▄▄█ █▄▄▄▄▄█ █▄▄█▄▄█ █▄▄▄▄▄█
soulseek-soulseek-1  | ╒════════════════════════════════════════════════════════╕
soulseek-soulseek-1  | │           GNU AFFERO GENERAL PUBLIC LICENSE            │
soulseek-soulseek-1  | │                   https://slskd.org                    │
soulseek-soulseek-1  | │                                                        │
soulseek-soulseek-1  | │              0.19.1.0 (0.19.1.0+8438098e)              │
soulseek-soulseek-1  | └────────────────────────────────────────────────────────┘
soulseek-soulseek-1  | [19:57:38 INF] Version: 0.19.1.0 (0.19.1.0+8438098e)
soulseek-soulseek-1  | [19:57:38 INF] System: .NET 7.0.13, Unix 6.2.6.1, 64 bit, 8 processors
soulseek-soulseek-1  | [19:57:38 INF] Process ID: 7 (64 bit)
soulseek-soulseek-1  | [19:57:38 INF] Invocation ID: 6987bdbb-9d31-4432-b24f-c82dc3a12dbb
soulseek-soulseek-1  | [19:57:38 INF] Instance Name: default
soulseek-soulseek-1  | [19:57:38 INF] Configuring application...
soulseek-soulseek-1  | [19:57:38 INF] Using application directory /app
soulseek-soulseek-1  | [19:57:38 INF] Using configuration file /app/slskd.yml
soulseek-soulseek-1  | [19:57:38 INF] Storing application data in /app/data
soulseek-soulseek-1  | [19:57:39 INF] Listening for HTTP requests at http://0.0.0.0:5030/
soulseek-soulseek-1  | [19:57:39 INF] Using base url /
soulseek-soulseek-1  | [19:57:39 INF] Serving static content from /slskd/wwwroot
soulseek-soulseek-1  | [19:57:39 INF] Configuration complete.  Starting application...
soulseek-soulseek-1  | [19:57:39 INF] Application started
soulseek-soulseek-1  | [19:57:40 INF] Listening for incoming connections on port 50300
soulseek-soulseek-1  | [19:57:40 INF] Initializing shares
soulseek-soulseek-1  | [19:57:40 INF] Share cache StorageMode is 'Disk'. Attempting to validate...
soulseek-soulseek-1  | [19:57:40 INF] Share cache loaded from disk successfully. Sharing 69 directories and 158 files
soulseek-soulseek-1  | [19:57:40 INF] Warming browse response cache...
soulseek-soulseek-1  | [19:57:40 INF] Browse response cached successfully in 53ms
soulseek-soulseek-1  | [19:57:40 FTL] Application terminated unexpectedly
soulseek-soulseek-1  | Soulseek.AddressException: Failed to resolve address '': Resource temporarily unavailable
soulseek-soulseek-1  |  ---> System.Net.Sockets.SocketException (00000001, 11): Resource temporarily unavailable
soulseek-soulseek-1  |    at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, Int64 startingTimestamp)
soulseek-soulseek-1  |    at System.Net.Dns.GetHostEntry(String hostNameOrAddress, AddressFamily family)
soulseek-soulseek-1  |    at Soulseek.SoulseekClient.ConnectAsync(String address, Int32 port, String username, String password, Nullable`1 cancellationToken)
soulseek-soulseek-1  |    --- End of inner exception stack trace ---
soulseek-soulseek-1  |    at Soulseek.SoulseekClient.ConnectAsync(String address, Int32 port, String username, String password, Nullable`1 cancellationToken)
soulseek-soulseek-1  |    at Soulseek.SoulseekClient.ConnectAsync(String username, String password, Nullable`1 cancellationToken)
soulseek-soulseek-1  |    at slskd.Application.Microsoft.Extensions.Hosting.IHostedService.StartAsync(CancellationToken cancellationToken)
soulseek-soulseek-1  |    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
soulseek-soulseek-1  |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
soulseek-soulseek-1  |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
soulseek-soulseek-1  |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
soulseek-soulseek-1  |    at slskd.Program.Main(String[] args)
soulseek-soulseek-1 exited with code 0
```

**Comment by melvyn2** [comment]
For some reason turning off share scanning on start (`SLSKD_NO_SHARE_SCAN=true`) makes this less likely to occur.

**Comment by mikew** [comment]
Huh, I'll give that a whirl but this might be because I can't communicate to soulseek.

https://www.reddit.com/r/Soulseek/s/bZoK0awQ7c

https://www.reddit.com/r/Soulseek/s/rrlZVRyaw5

**Comment by jpdillingham** [comment]
This looks like an uncaught error resulting from the Soulseek server address DNS resolution failing.  I'll have to clean this up so the root cause is more clear, but it'll continue to happen until DNS is fixed.

**Comment by mikew** [comment]
Thanks for the response! I didn't notice until after I created the issue that the update check was a bit of a red herring, and that the underlying issue was the same in both cases, which prompted me to investigate further

**Comment by jpdillingham** [comment]
#998 updates the underlying library Soulseek.NET to improve the error message; the root cause was a DNS issue causing the hard-coded server address lookup to fail.

The 403 from GitHub is interesting; unless you had been restarting a _lot_ it must be using the user agent to apply rate limits across distributed clients.  Either way there's no ill effect if it fails.

I'm going to add the ability to set the server address and port in the configuration; it would have allowed users to connect during this outage if they knew the correct IP address.
